In [3]:
# 1. 10, 7, 5, 90, 100 을 가지는 1차원 배열을 생성.
import numpy as np
arr1=np.array([10, 7, 5, 90, 100])
arr1.shape

(5,)

In [7]:
#2. 100 ~ 200 범위의 숫자중 짝수를 가지는 배열을 생성.
arr = np.arange(100,201,2)
print(arr)
print(arr.shape)

[100 102 104 106 108 110 112 114 116 118 120 122 124 126 128 130 132 134
 136 138 140 142 144 146 148 150 152 154 156 158 160 162 164 166 168 170
 172 174 176 178 180 182 184 186 188 190 192 194 196 198 200]
(51,)


In [16]:
arr1 = np.linspace(100,200,num=51,retstep=True) #linspace(start,end,num=50,retstep=False,endpoit=True,dtype=none)
arr1

(array([100., 102., 104., 106., 108., 110., 112., 114., 116., 118., 120.,
        122., 124., 126., 128., 130., 132., 134., 136., 138., 140., 142.,
        144., 146., 148., 150., 152., 154., 156., 158., 160., 162., 164.,
        166., 168., 170., 172., 174., 176., 178., 180., 182., 184., 186.,
        188., 190., 192., 194., 196., 198., 200.]),
 2.0)

In [10]:
#3. 2번에서 생성한 배열과 동일한 shape에 0을 원소로 가지는 배열 생성.
a = np.zeros(arr.shape)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
b = np.zeros_like(arr)
b

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0])

In [19]:
a1= np.zeros(51,)
a1.shape


(51,)

In [29]:
#4. 1001 ~ 10000 범위의 정수 중 100의 배수만 가지는 3차원 배열을 생성. (shape은 상관없음.)
arr = np.arange(1000,10001,100)
print(arr)
print(arr.shape)
arr1 =np.linspace(1000,10000,num=91,retstep=True,dtype=float)
arr1


[ 1000  1100  1200  1300  1400  1500  1600  1700  1800  1900  2000  2100
  2200  2300  2400  2500  2600  2700  2800  2900  3000  3100  3200  3300
  3400  3500  3600  3700  3800  3900  4000  4100  4200  4300  4400  4500
  4600  4700  4800  4900  5000  5100  5200  5300  5400  5500  5600  5700
  5800  5900  6000  6100  6200  6300  6400  6500  6600  6700  6800  6900
  7000  7100  7200  7300  7400  7500  7600  7700  7800  7900  8000  8100
  8200  8300  8400  8500  8600  8700  8800  8900  9000  9100  9200  9300
  9400  9500  9600  9700  9800  9900 10000]
(91,)


(array([ 1000.,  1100.,  1200.,  1300.,  1400.,  1500.,  1600.,  1700.,
         1800.,  1900.,  2000.,  2100.,  2200.,  2300.,  2400.,  2500.,
         2600.,  2700.,  2800.,  2900.,  3000.,  3100.,  3200.,  3300.,
         3400.,  3500.,  3600.,  3700.,  3800.,  3900.,  4000.,  4100.,
         4200.,  4300.,  4400.,  4500.,  4600.,  4700.,  4800.,  4900.,
         5000.,  5100.,  5200.,  5300.,  5400.,  5500.,  5600.,  5700.,
         5800.,  5900.,  6000.,  6100.,  6200.,  6300.,  6400.,  6500.,
         6600.,  6700.,  6800.,  6900.,  7000.,  7100.,  7200.,  7300.,
         7400.,  7500.,  7600.,  7700.,  7800.,  7900.,  8000.,  8100.,
         8200.,  8300.,  8400.,  8500.,  8600.,  8700.,  8800.,  8900.,
         9000.,  9100.,  9200.,  9300.,  9400.,  9500.,  9600.,  9700.,
         9800.,  9900., 10000.]),
 100.0)

In [36]:
#5. (4,4) 형태의 단위행렬(항등행렬)을 생성.
print(np.eye(4,4,2))
print(np.identity(4)) # np.identity(n, dtype=None)

[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [40]:
# 6. 다음 값을 가지는 배열을 생성하고 배열의 차원수(rank)와 형태, 총 원소(element)의 개수를 조회.
# 20, 90, 80, 100, -20, 30
# 50, -10, 25, 120, -40, 90

arr=np.array([[20, 90, 80, 100, -20, 30],
         [50, -10, 25, 120, -40, 90]])
print(arr)
print(arr.shape)
print(arr.size)
print(arr.ndim)

[[ 20  90  80 100 -20  30]
 [ 50 -10  25 120 -40  90]]
(2, 6)
12
2


In [43]:
#7. 정규분포를 따르는 난수를 가지는 (3,2,7) 형태의 배열을 생성.
arr=np.random.normal(3,2,7)  # normal(loc=0.0, scale=1.0, size=None)  ->defalt값
arr

array([3.10670276, 4.17392382, 1.57705372, 0.8437521 , 6.40882277,
       1.24958505, 4.59129589])

In [46]:
#8. 1 ~ 100 사이의 정수 난수를 가지는 (4, 5) 형태의 배열을 생성한 뒤 arr.npy 파일로 저장.
arr = np.random.randint(1,100,size=(4,5))
arr
np.save('arr.npy',arr) # np.save('파일명',arr) --->
np.load('arr.npy')

array([[93, 92, 63, 16, 63],
       [39, 32, 36, 18, 11],
       [75, 58, 40, 67, 12],
       [87, 33, 94, 15, 92]])

In [ ]:
9. 8번에서 저장한 arr.npy 의 배열을 불러와서 출력.

In [48]:
#10. 9번에서 불러온 배열에서 전체 값의 총합, 0번축 기준의 총합, 1번축 기준의 총합을 구하기.
np.sum(arr),np.sum(arr,axis=1)

(1036, array([327, 136, 252, 321]))

In [59]:
#11. 임의의 Boolean 값을 가지는 (5, 10) 배열을 생성하고 True의 개수를 출력하시오.
arr=np.random.choice([True,False],(5,10))  #choice(a, size=None, replace=True, p=None)
print(arr)
print(arr.sum())


[[ True False False  True  True False  True False False False]
 [False False False  True False False False False  True False]
 [ True False False  True  True  True False  True False False]
 [False False  True False  True False  True  True False  True]
 [ True False  True  True False False  True  True  True False]]
22


In [58]:
# 12-17. 아래 배열을 생성하고 12번 ~ 17번 문제는 아래 조건으로 생성한 배열을 가지고 푸세요.
#  0 ~ 29 범위의 정수를 원소로 가지는 (5,6) 의 배열을 생성하고 변수에 저장.
arr = np.arange(0,30).reshape(5,6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [65]:
ar = np.random.randint(0,30,size=(5,6))
ar

array([[10, 24, 26, 17, 27,  2],
       [ 5, 11, 18,  1,  4, 26],
       [ 3, 16, 12, 15, 14, 25],
       [11, 18, 10,  5,  1, 19],
       [ 7, 25, 29,  1, 12,  8]])

In [68]:
#12. index (1,1), (2,3), (1,5)의 값들 조회
ar[[1,2,1],[1,3,5]]

array([11, 15, 26])

In [71]:
#13. index (1,1), (1,2), (1,3), (2,1), (2,2), (2,3), (3,1), (3,2), (3,3)의 값들을 조회.
a=ar[1:4,1:4]
a

array([[11, 18,  1],
       [16, 12, 15],
       [18, 10,  5]])

In [73]:
#14. 13와 같은 index의 값들을 뒤집어서(reversing) 조회.
np.flip(a)

array([[ 5, 10, 18],
       [15, 12, 16],
       [ 1, 18, 11]])

In [79]:
#15. 배열에서 15 이상의 원소만 조회해서 그 평균을 출력.
p=np.mean(ar[ar>=15])
print(np.round(p,2))
print(ar[ar>=15])

21.92
[24 26 17 27 18 26 16 15 25 18 19 25 29]


In [87]:
#16. 배열에서 15이상의 원소들의 index를 조회. (0축 index, 1축 index) 형식으로 출력. 
 #   ex: (0,0), (0,1) 식으로 출력
kd=np.where(ar>=15)
kd

(array([0, 0, 0, 0, 1, 1, 2, 2, 2, 3, 3, 4, 4], dtype=int64),
 array([1, 2, 3, 4, 2, 5, 1, 3, 5, 1, 5, 1, 2], dtype=int64))

In [89]:
for i in zip(kd[0],kd[1]):
    print (i)

(0, 1)
(0, 2)
(0, 3)
(0, 4)
(1, 2)
(1, 5)
(2, 1)
(2, 3)
(2, 5)
(3, 1)
(3, 5)
(4, 1)
(4, 2)


In [93]:
# 17. 배열을 axis 1을 기준으로 내림차순으로 정렬. 
# 결과
# [[ 5,  4,  3,  2,  1,  0],
#  [11, 10,  9,  8,  7,  6],
#  [17, 16, 15, 14, 13, 12],
#  [23, 22, 21, 20, 19, 18],
#  [29, 28, 27, 26, 25, 24]]   
arr = np.array([[ 5,  4,  3,  2,  1,  0],
                 [11, 10,  9,  8,  7,  6],
                 [17, 16, 15, 14, 13, 12],
                 [23, 22, 21, 20, 19, 18],
                [29, 28, 27, 26, 25, 24]] 
                )

arr.sort()
arr[::,::-1]

array([[ 5,  4,  3,  2,  1,  0],
       [11, 10,  9,  8,  7,  6],
       [17, 16, 15, 14, 13, 12],
       [23, 22, 21, 20, 19, 18],
       [29, 28, 27, 26, 25, 24]])

In [95]:
# 18-21. 아래 배열을 생성하고 18번 ~ 21번 문제는 아래 조건으로 생성한 배열을 가지고 푸세요.
# (3, 2) shape의 배열을 생성 하시오. 

arr = np.random.randint(1,30,size=(3,2))
arr.shape

(3, 2)

In [108]:
#18. 배열의 shape을 (1, 3, 2) 로 변환한 배열을 생성.
arr1=arr[np.newaxis,...]
arr1.shape

(1, 3, 2)

In [110]:
arr2=arr[np.newaxis,:,:]
arr2.shape

(1, 3, 2)

In [114]:
#19. 배열의 shape을 (1, 3, 2, 1) 로 변환한 배열을 생성.
a=arr[np.newaxis,:,:,np.newaxis]
a.shape

(1, 3, 2, 1)

In [118]:
#20. 배열을 1차원 배열로 변환한 배열을 생성.
a =arr.flatten()
print(a)
arr

[ 6 18 14 15 23 21]


array([[ 6, 18],
       [14, 15],
       [23, 21]])

In [122]:
#21. 배열의 0번 축에 2개의 값을 추가. (추가된 배열의 shape: (5,2))//
np.insert(arr,3,[[1,2],[3,4]],axis=0)
np.append(arr,[[1,2],[3,4]],axis=0)

array([[ 6, 18],
       [14, 15],
       [23, 21],
       [ 1,  2],
       [ 3,  4]])

In [127]:
ar1=np.insert(arr,1,[[1,1,1],[2,2,2],[3,3,3]],axis=1)
ar1

array([[ 6,  1,  2,  3, 18],
       [14,  1,  2,  3, 15],
       [23,  1,  2,  3, 21]])

In [132]:
a= np.arange(0,20).reshape(1,2,2,1,1,5)
np.squeeze(a).shape

(2, 2, 5)

In [135]:
np.squeeze(a,axis=4).shape


(1, 2, 2, 1, 5)

In [136]:
#22-28. 다음 배열은 5명 학생의 국어, 영어, 수학, 과학 시험 점수이다. 행(axis=0)은 각 학생의 시험점수이고 컬럼(axis=1)은 과목을 가리킨다.

score= np.array([
 [ 60,  80,  60, 100],
 [ 80,  80,  90,  90],
 [ 90,  60,  70,  50],
 [ 40,  80,  60,  50],
 [ 60,  50,  70, 100]
])

In [137]:
score

array([[ 60,  80,  60, 100],
       [ 80,  80,  90,  90],
       [ 90,  60,  70,  50],
       [ 40,  80,  60,  50],
       [ 60,  50,  70, 100]])

In [147]:
#22. 각 과목별 평균점수를 조회.
p= np.mean(score,axis=0)
p

array([66., 70., 70., 78.])

In [142]:
np.add.reduce(score,axis=0)/5

array([66., 70., 70., 78.])

In [149]:
#23. 각 과목별 평균 점수를 성적 배열에 추가. 
np.append(score,[p],axis=0)  # 차원수를 맞춰줬어야함 

array([[ 60.,  80.,  60., 100.],
       [ 80.,  80.,  90.,  90.],
       [ 90.,  60.,  70.,  50.],
       [ 40.,  80.,  60.,  50.],
       [ 60.,  50.,  70., 100.],
       [ 66.,  70.,  70.,  78.]])

In [144]:
np.add.reduce(score,axis=1)

array([300, 340, 270, 230, 280])

In [150]:
score

array([[ 60,  80,  60, 100],
       [ 80,  80,  90,  90],
       [ 90,  60,  70,  50],
       [ 40,  80,  60,  50],
       [ 60,  50,  70, 100]])

In [ ]:
24. 각 학생들의 평균 점수 조회

In [153]:
stud_mean = np.mean(score,axis=1)
stud_mean

array([75. , 85. , 67.5, 57.5, 70. ])

In [166]:
#25. 과목별로 몇번째 학생의 성적이 가장 높은지 조회
print(np.max(score,axis=0))
print(np.argmax(score,axis=0)+1)


[ 90  80  90 100]
[3 1 2 1]


In [164]:
#np.where() --> bool 조건에 True 인 값의 인덱스를 알려줌

(array([0], dtype=int64),)

In [168]:
#26. 학생별로 어떤 과목의 점수가 가장 낮은지 조회.
np.argmin(score,axis=1)

array([0, 0, 3, 0, 1], dtype=int64)

In [169]:
sub = np.array(['국어', '영어', '수학', '과학'])
sub[np.argmin(score,axis=1)] # fancy indexing 한다고 생각하면 됨

array(['국어', '국어', '과학', '국어', '영어'], dtype='<U2')

In [170]:
score

array([[ 60,  80,  60, 100],
       [ 80,  80,  90,  90],
       [ 90,  60,  70,  50],
       [ 40,  80,  60,  50],
       [ 60,  50,  70, 100]])

In [172]:
#27. 각 과목별로 편차가 가장 적은 과목과 가장 큰 과목을 조회
np.argmax(np.std(score,axis=0))

3

In [174]:
np.argmin(np.std(score,axis=0))

2

In [173]:
sub[np.argmax(np.std(score,axis=0))]

'과학'

In [175]:
#28. 학생들 중 과목간의 점수의 편차가 가장 적은 학생을 조회
np.argmin(np.std(score,axis=1))

1

In [177]:
#29-30 다음 두 배열을 가지고 29,30번 문제를 푸세요.
a=np.array(
[
  [1,2,3],
  [4,5,6],
  [7,8,9]
])

b= np.array(
[
  [10,20,30],
  [40,50,60],
  [70,80,90]
])

In [178]:
a,b

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]]))

In [181]:
#29. 두 배열을 수직방향으로 합치기. 
ab=np.concatenate((a,b),axis=0)
ab

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [183]:
#30. 29에서 합친 배열을 수평방향으로 index 2를 기준으로 나누기.
np.split(ab,[2])

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]])]

In [184]:
#31-32 다움은 7명의 학생의 점수이다. 배열을 생성한뒤 33번 ~ 35번 문제를 푸세요.
sc = np.array([10, 50, 75, 20, 70, 50, 80])

In [188]:
#31. 다음 배열에서 평균 이상의 점수를 받은 학생이 몇명인지 조회
aver=np.round(np.mean(sc),2)
aver

50.71

In [189]:
np.sum(sc>=aver)

3

In [191]:
#32. 다음 배열에서 평균 이상의 점수를 받은 학생이 전체 학생 중 몇명인지 비율을 조회.
np.mean(sc>=aver)

0.42857142857142855

In [192]:
np.mean(sc)

50.714285714285715

In [195]:
#33-35 다음 배열은 스무명의 사람들의 연봉의 표본이다. (단위 만원) 배열을 생성한뒤 33번 ~ 35번 문제를 푸세요.
salary =np.array([7650, 4210, 7260, 8020, 8200, 8740, 4960, 1420,
 5410, 9770, 2370, 7960, 8960, 2660, 7940, 5120,
 7100, 5220, 8810, 253000])

salary

array([  7650,   4210,   7260,   8020,   8200,   8740,   4960,   1420,
         5410,   9770,   2370,   7960,   8960,   2660,   7940,   5120,
         7100,   5220,   8810, 253000])

In [196]:
#33. 위 배열에서 상위 75% 는 얼마 이상을 받는지 조회.
np.quantile(salary,q=0.75)

8335.0

In [198]:
#34. 위 배열에서 하위 25%는 얼마 이하를 받는지 조회.
np.quantile(salary,q=0.25)

5080.0

In [199]:
#35. 위 배열의 평균과 중앙값을 구하고 배열의 대푯값으로 어떤 것을 사용하는 것이 맞는지 적으세요.
np.mean(salary)

18739.0

In [200]:
np.median(salary)

7455.0