# 인덱싱과 슬라이싱을 이용한 배열의 원소 조회

## 배열 인덱싱(Indexing)
- ### index
    - 배열내의 원소의 식별번호
    - 0부터 시작
    - 뒤에서 부터는 -1로 시작
- ### indexing 
    – index를 이용해 원소 조회
    - [] 표기법 사용
- ### 구문 
    - ndarray[index]
    - 양수는 지정한 index의 값을 조회한다. 
    - 음수는 뒤부터 조회한다. 
        - 마지막 index가 -1
    - 2차원배열의 경우 
        - arr[행index, 열index]
        - 파이썬 리스트와 차이점 (list[행][열])
    - N차원 배열의 경우
        - arr[0축 index, 1축 index, ..., n축 index]
- ### 팬시(fancy) 인덱싱
    - <<<<**여러개의 원소를 한번에 조회**>>>할 경우 리스트에 담아 전달한다.
    - 다차원 배열의 경우 각 축별로 list로 지정
    - `arr[[1,2,3,4,5]]`
        - 1차원 배열(vector): 1,2,3,4,5 번 index의 원소들 한번에 조회
    - `arr[[0,3],[ 1,4]]`
        - [0,3] - 1번축 index list, [1,4] - 2번축 index list
        - 2차원 배열(matrix): [0,1], [3,4] 의 원소들 조회

In [6]:
lst = [
    [1,2,3],
    [4,5,6]
]
print(lst[0])
print(lst[0][0],lst[1][2])   # 리스트에서 

[1, 2, 3]
1 6


In [7]:
import numpy as np

In [8]:
a= np.array(lst)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
print(a[0,0],a[1,2])    #각각 a의 인덱스 연산자에 넣었음.

1 6


In [12]:
print(a[[0,0],[1,2]])  # 하나의 인덱스 연산자에 넣었을때  #[0번축,1번축]

[2 3]


In [90]:
b = np.arange(12).reshape(2,2,3)
print(b.shape)
b

(2, 2, 3)


array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [94]:
b[[0,1],[0,0],[2,1]]

array([2, 7])

In [101]:
c=np.arange(5).reshape(5,)
c

array([0, 1, 2, 3, 4])

In [99]:
c[[0,4]]

array([0, 4])

In [95]:
print(b[0,0,1], b[0][0][1], b[1,0,1])  # 두가지 방법이있다.  // 연습해보자~!

1 1 7


In [19]:
print(b[1,0],b[0,1])   #축이 3개인데  값을 2개 만주면 배열을 갖고 오겠다~!

[6 7 8] [3 4 5]


In [20]:
b[0]  # 1개의 값이다.//꼭 원소만 갖고 오는게 아니라 배열을 갖고올 수도 있다~!

array([[0, 1, 2],
       [3, 4, 5]])

In [23]:
arr = np.arange(11,20)
arr #1차원

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [24]:
arr[[1,3]]

array([12, 14])

In [102]:
k=np.arange(3,10)
k

array([3, 4, 5, 6, 7, 8, 9])

In [108]:
# 4 인덱싱
k[1]

4

In [109]:
# 4,7,9 인덱싱
k[[1,-3,-1]]  #fancy 인덱싱에서는  조회하고 싶은 원소의 인덱스를 리스트로 묶어서 인덱스 연산자[]안에 넣어준다.

array([4, 7, 9])

In [115]:
k1=np.arange(36).reshape(3,4,3)
k1

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [120]:
# 9인덱싱
k1[0,3,0]

9

In [121]:
#11인덱싱
k1[0,3,2]

11

In [122]:
#30인덱싱
k1[2,2,0]

30

In [118]:
k1

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [123]:
#0,5,20,18 인덱싱
k1[[0,0,1,1],[0,1,2,2],[0,2,2,0]]

array([ 0,  5, 20, 18])

In [124]:
#13,2,29 인덱싱
k1[[1,0,2],[0,0,1],[1,2,2]]

array([13,  2, 29])

In [125]:
#35,19,5 인덱싱
k1[[2,1,0,],[3,2,1],[2,1,2]]

array([35, 19,  5])

### 팬시(fancy) 인덱싱

In [23]:
arr[[0,2]]   # [  ] -> 인덱스 연산자 안에  [조회하고 싶은 인덱스 (여러개)] 를 리스트로 넣어준다.

array([0, 2])

In [24]:
arr[[0,5,7]]

array([0, 5, 7])

In [27]:
arr2 = np.arange(12).reshape(3,4)
print(arr2.shape)
print(arr2)

(3, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [32]:
#3,4,9
arr2[[0,1,2],[3,0,1]]

array([3, 4, 9])

In [30]:
arr2[0,1] , arr2[2,3]

(1, 11)

In [31]:
# 1,11 을 갖고 오고 싶을때  // , 를 기준으로 앞은 0번축 인덱스만 그다음 1번축 인덱스만 넣을 수 있다.
arr2[[0,2],[1,3]]


array([ 1, 11])

In [33]:
arr2[[1,2,0],[0,1,3]]   # 3차원 만들어서 연습하기!

array([4, 9, 3])

In [34]:
print(arr2[1,0],arr2[2,1],arr2[0,3])

4 9 3


In [ ]:
# 배열 [0xis,1xis,2xis] 

In [37]:
arr[1] = 100   # 값 변경(대입)
arr

array([  0, 100,   2,   3,   4,   5,   6,   7,   8,   9])

In [39]:
arr[2],arr[4] = 200,400  # 튜플 대입
arr

array([  0, 100, 200,   3, 400,   5,   6,   7,   8,   9])

In [40]:
arr[[5,7]]  = 500,700  # 팬시 인덱싱 이용해서 바꿀 수도 있다.
arr

array([  0, 100, 200,   3, 400, 500,   6, 700,   8,   9])

In [127]:
k

array([3, 4, 5, 6, 7, 8, 9])

In [132]:
k[0] = 900815
print(k)
k

[900815      4      5      6      7      8      9]


array([900815,      4,      5,      6,      7,      8,      9])

In [135]:
k[[-1,2]]=300,345
k

array([900815,      4,    345,      6,      7,      8,    300])

In [138]:
k[[0,3,5]] =1,2,3
k

array([  1,   4, 345,   2,   7,   3, 300])

In [144]:
k1

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,  90],
        [  9,  10,  11]],

       [[ 12,  13,  14],
        [ 15, 100,  17],
        [ 18,  19,  20],
        [ 21,  22,  23]],

       [[ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  87,  32],
        [ 33,  34,  35]]])

In [139]:
# 값변경 8->90
k1[0,2,2]=90

In [141]:
#31-> 87
k1[2,2,1]=87

In [143]:
#16->100
k1[1,1,1]= 100

In [148]:
k1

array([[[   0,    1,    2],
        [   3,    4,   59],
        [   6,    7,   90],
        [   9,   10,   11]],

       [[  12,   13,   14],
        [  15,  100,   17],
        [  18,   19,   20],
        [  21,   48,   23]],

       [[  24,   25,   26],
        [  27,   28,   29],
        [3000,   87,   32],
        [  33,   34,   35]]])

In [147]:
#fancy index이용해서 값 여러개 한번에 변경
#5,22,30 -> 59,48,3000
k1[[0,1,2],[1,3,2],[2,1,0]] = 59,48,3000

## 슬라이싱
- 배열의 부분 집합을 하위배열로 조회 및 변경하는 방식
- ndarry[start : stop : step ]
    - start : 시작 인덱스. 기본값 0
    - stop : 끝 index. stop은 포함하지 않는다. 기본값 마지막 index
    - step : 증감 간격. 기본값 1)

In [41]:
arr = np.arange(100)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [43]:
arr[3:10]

array([3, 4, 5, 6, 7, 8, 9])

In [45]:
arr[:10]  

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
arr[50:]    # stop index 생략시 끝까지 갖고오는 것 

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [47]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [48]:
arr[5:61:2]

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59])

In [49]:
arr[::10]

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [50]:
arr[50:20:-1]  #step 을 안넣으면 기본값 1 이라 안됨 ㅜ// step 음수 : 리버스(뒤집기), start> stop

array([50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34,
       33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21])

In [51]:
arr[::-1] # 전체적으로 reverse 할때 start,stop 생략

array([99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83,
       82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66,
       65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49,
       48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [52]:
arr[-1]

99

In [53]:
arr[-1:50:-1]

array([99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83,
       82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66,
       65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51])

In [54]:
arr[99:50:-1]

array([99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83,
       82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66,
       65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51])

### 다차원 배열 슬라이싱
- 각 축에 slicing 문법 적용
- 2차원의 경우
    - arr [행 slicing, 열 slicing]
        - `arr[:3, :]`
    - `,` 로 행과 열을 구분한 다중 슬라이싱 사용
- 다차원의 경우
    - arr[0축 slicing, 1축 slicing, ..., n축 slicing]
- slicing과 indexing 문법은 같이 쓸 수 있다.
- 모든 축에 index를 지정할 필요는 없다.

In [26]:
a[2:5,2:4,:2]    # , 를 기준으로 축별 인덱스 넣어서 슬라이싱
a[[2,3,4],[2,3]]

IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed

In [25]:
a= np.arange(30).reshape(6,5)
print(a.shape)
print(a)


(6, 5)
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


In [27]:
a[2:5,2:4]

array([[12, 13],
       [17, 18],
       [22, 23]])

In [61]:
a[1:5,0:]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [62]:
a[1:5]  # 마지막축 생략 가능

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [63]:
a[:, 1:3]

array([[ 1,  2],
       [ 6,  7],
       [11, 12],
       [16, 17],
       [21, 22],
       [26, 27]])

In [64]:
a[,1:3]  # 뒤쪽 축은 생략 가능하지만 앞쪽축은 생략할 수 없다.

SyntaxError: invalid syntax (<ipython-input-64-d5285043fb33>, line 1)

In [65]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [66]:
a[:,[1,2]]  # 0 번축 슬라이싱 1번축 팬시 인덱싱

array([[ 1,  2],
       [ 6,  7],
       [11, 12],
       [16, 17],
       [21, 22],
       [26, 27]])

In [ ]:
#6   7  8 을 갖고올때

#11 12 13 을 갖고올때

#16 17 18 을 갖고올때

#21 22 23 을 갖고올때


In [59]:
a[1:5,1:4]

array([[ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18],
       [21, 22, 23]])

In [67]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [68]:
a[:, ::-1]

array([[ 4,  3,  2,  1,  0],
       [ 9,  8,  7,  6,  5],
       [14, 13, 12, 11, 10],
       [19, 18, 17, 16, 15],
       [24, 23, 22, 21, 20],
       [29, 28, 27, 26, 25]])

In [69]:
a[::-1,:]

array([[25, 26, 27, 28, 29],
       [20, 21, 22, 23, 24],
       [15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

In [71]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [70]:
a[::-1,::-1]

array([[29, 28, 27, 26, 25],
       [24, 23, 22, 21, 20],
       [19, 18, 17, 16, 15],
       [14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [72]:
np.flip(a)      # 전체 다뒤집음

array([[29, 28, 27, 26, 25],
       [24, 23, 22, 21, 20],
       [19, 18, 17, 16, 15],
       [14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [150]:
a

array([[    0, 10000,     2,     3,     4],
       [    5,     6,     7,     8,     9],
       [   10,    11,    12,    13,    14],
       [   15,    16,    17,    18,    19],
       [   20,    21,    22,    23,    24],
       [   25,    26,    27,    28,    29]])

In [151]:
np.flip(a, axis=0)  # 0 번축만 뒤집어라

array([[   25,    26,    27,    28,    29],
       [   20,    21,    22,    23,    24],
       [   15,    16,    17,    18,    19],
       [   10,    11,    12,    13,    14],
       [    5,     6,     7,     8,     9],
       [    0, 10000,     2,     3,     4]])

In [149]:
np.flip(a, axis=1)   # 1번축만 뒤집어라

array([[    4,     3,     2, 10000,     0],
       [    9,     8,     7,     6,     5],
       [   14,    13,    12,    11,    10],
       [   19,    18,    17,    16,    15],
       [   24,    23,    22,    21,    20],
       [   29,    28,    27,    26,    25]])

In [154]:
k1= np.arange(45).reshape(3,3,5)
k1

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44]]])

In [159]:
#2,43  슬라이싱
k1[0:3,0:3,2:4]

array([[[ 2,  3],
        [ 7,  8],
        [12, 13]],

       [[17, 18],
        [22, 23],
        [27, 28]],

       [[32, 33],
        [37, 38],
        [42, 43]]])

In [ ]:
#1,28 슬라이싱

In [165]:
k1[0:2,0:3,1:4]

array([[[ 1,  2,  3],
        [ 6,  7,  8],
        [11, 12, 13]],

       [[16, 17, 18],
        [21, 22, 23],
        [26, 27, 28]]])

In [30]:
k3=np.arange(30).reshape(5,6)
k3


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [109]:
# 2~28슬라이싱 
k3[0:5,2:-1]

array([[ 2,  3,  4],
       [ 8,  9, 10],
       [14, 15, 16],
       [20, 21, 22],
       [26, 27, 28]])

In [110]:
#13~27 슬라이싱
k3[2:,1:-2]

array([[13, 14, 15],
       [19, 20, 21],
       [25, 26, 27]])

In [111]:
k3

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [175]:
#0~21 슬라이싱
k3[0:4,0:4:]

array([], shape=(4, 0), dtype=int32)

In [177]:
k3[::-1,]

array([[24, 25, 26, 27, 28, 29],
       [18, 19, 20, 21, 22, 23],
       [12, 13, 14, 15, 16, 17],
       [ 6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5]])

In [179]:
k3[::,::-1]

array([[ 5,  4,  3,  2,  1,  0],
       [11, 10,  9,  8,  7,  6],
       [17, 16, 15, 14, 13, 12],
       [23, 22, 21, 20, 19, 18],
       [29, 28, 27, 26, 25, 24]])

In [31]:
k3

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [180]:
k3[::-1,::-1]

array([[29, 28, 27, 26, 25, 24],
       [23, 22, 21, 20, 19, 18],
       [17, 16, 15, 14, 13, 12],
       [11, 10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1,  0]])

In [ ]:
np.flip(a) 
np.flip(a, axis=1) 
np.flip(a, axis=0)

In [182]:
k3

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [184]:
np.flip(k3)

array([[29, 28, 27, 26, 25, 24],
       [23, 22, 21, 20, 19, 18],
       [17, 16, 15, 14, 13, 12],
       [11, 10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1,  0]])

In [186]:
np.flip(k3,axis=0)

array([[24, 25, 26, 27, 28, 29],
       [18, 19, 20, 21, 22, 23],
       [12, 13, 14, 15, 16, 17],
       [ 6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5]])

In [187]:
np.flip(k3,axis=1)

array([[ 5,  4,  3,  2,  1,  0],
       [11, 10,  9,  8,  7,  6],
       [17, 16, 15, 14, 13, 12],
       [23, 22, 21, 20, 19, 18],
       [29, 28, 27, 26, 25, 24]])

### 슬라이싱은 원본에 대한 View 
- slicing한 결과는 새로운 배열을 생성하는 것이 아니라 기존 배열을 참조한다.  (슬라이싱 한 부분만 보고 있는 것이다 라고 생각하면됨)
- slicing한 배열의 원소를 변경하면 원본 배열의 것도 바뀐다. 전체에서 슬라이싱한 부분만 그냥 보는것 이기때문에 // 조회만 할때 더 유리하다./메모리를 안    차지 하니까
- 배열.copy()
    - 배열을 복사한 새로운 배열 생성  // 원소 변경까지 하고 싶다면 
    - 복사후 처리하면 원본이 바뀌지 않는다.  (deep copy)

In [103]:
import numpy as np

In [188]:
a

array([[    0, 10000,     2,     3,     4],
       [    5,     6,     7,     8,     9],
       [   10,    11,    12,    13,    14],
       [   15,    16,    17,    18,    19],
       [   20,    21,    22,    23,    24],
       [   25,    26,    27,    28,    29]])

In [80]:
b= a[:,1:4]
print(b.shape)
b   # 새로운게 만들어져서 b가 된게 아니라 단지 a의 슬라이싱 된부분만 view 보여주는 것이다. 그래서 b 의 값을 바꾸면 a도 바뀐다.

(6, 3)


array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18],
       [21, 22, 23],
       [26, 27, 28]])

In [81]:
b[0,0] =10000 # a도 바뀐다
b

array([[10000,     2,     3],
       [    6,     7,     8],
       [   11,    12,    13],
       [   16,    17,    18],
       [   21,    22,    23],
       [   26,    27,    28]])

In [82]:
a

array([[    0, 10000,     2,     3,     4],
       [    5,     6,     7,     8,     9],
       [   10,    11,    12,    13,    14],
       [   15,    16,    17,    18,    19],
       [   20,    21,    22,    23,    24],
       [   25,    26,    27,    28,    29]])

In [83]:
a

array([[    0, 10000,     2,     3,     4],
       [    5,     6,     7,     8,     9],
       [   10,    11,    12,    13,    14],
       [   15,    16,    17,    18,    19],
       [   20,    21,    22,    23,    24],
       [   25,    26,    27,    28,    29]])

In [85]:
b= a[:,1:4]
b = b.copy()   # 필요한 값 슬라이싱 한후 카피 함 .

In [86]:
b

array([[10000,     2,     3],
       [    6,     7,     8],
       [   11,    12,    13],
       [   16,    17,    18],
       [   21,    22,    23],
       [   26,    27,    28]])

In [87]:
b[0,0] = 5000   # 슬라이싱 한후 카피 함 .#카피본의 값을 변경한것이다 a(원본) 는 그대로 
b

array([[5000,    2,    3],
       [   6,    7,    8],
       [  11,   12,   13],
       [  16,   17,   18],
       [  21,   22,   23],
       [  26,   27,   28]])

In [183]:
a

array([[    0, 10000,     2,     3,     4],
       [    5,     6,     7,     8,     9],
       [   10,    11,    12,    13,    14],
       [   15,    16,    17,    18,    19],
       [   20,    21,    22,    23,    24],
       [   25,    26,    27,    28,    29]])

In [33]:
k3

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [ ]:
# 슬라잉싱 해서 값 바꾸기  // 슬라이싱은 원본값이 같이 바뀜 /슬라이싱 한부분만 보여주는 원리라서 

In [41]:
k3

array([[  0,   1,   2,   3,   4,   5],
       [  6,   7,  80,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21, 220,  23],
       [ 24,  25,  26,  27,  28,  29]])

In [42]:
d = k3[0:5,0]
d

array([ 0,  6, 12, 18, 24])

In [40]:
#8,22를 80,220 으로 바꾸기
k3[[1,3],[2,-2]] = 80,220
k3

array([[  0,   1,   2,   3,   4,   5],
       [  6,   7,  80,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21, 220,  23],
       [ 24,  25,  26,  27,  28,  29]])

In [43]:
#15를 150으로 바꾸기 
d[2,2] = 150

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [198]:
k3

array([[  0,   1,   2,   3,   4,   5],
       [  6,   7,  80,   9,  10,  11],
       [ 12,  13,  14, 150,  16,  17],
       [ 18,  19,  20,  21, 220,  23],
       [ 24,  25,  26,  27,  28,  29]])

In [ ]:
#.copy 해서 값 바꾸기 // 원본은 절대 바뀌지 않음 슬라이싱 한부분을 카피하여 새로운 객체를 만들어 값을 변경했기 때문 

In [44]:
k3

array([[  0,   1,   2,   3,   4,   5],
       [  6,   7,  80,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21, 220,  23],
       [ 24,  25,  26,  27,  28,  29]])

In [45]:
d1=k3[0:4,3:]
d1=d1.copy()

#d1 = k3[0:4,3:].copy 해도 됨~!!

In [203]:
d1

array([[  3,   4,   5],
       [  9,  10,  11],
       [150,  16,  17],
       [ 21, 220,  23]])

In [46]:
#16,23,11 을 160,230,110 으로 바꾸기

d1[[2,3,1],[1,2,2]] = 160,230,110

In [47]:
print(d1)
print(k3)

[[  3   4   5]
 [  9  10 110]
 [ 15 160  17]
 [ 21 220 230]]
[[  0   1   2   3   4   5]
 [  6   7  80   9  10  11]
 [ 12  13  14  15  16  17]
 [ 18  19  20  21 220  23]
 [ 24  25  26  27  28  29]]


In [ ]:
슬라이싱과 인덱싱을 섞어서 할수 있다. 오늘 복습때 해보기 

## boolean indexing
- Index 연산자"[]"에 Boolean 배열을 넣으면 ""**True인 index의 값**""만 조회 (False가 있는 index는 조회하지 않는다.)
- ndarray내의 원소 중에서 원하는 조건의 값들만 조회할 때 사용

In [2]:
import numpy as np

In [4]:
a = np.array([1,2,3,4,5])
a.shape

(5,)

In [5]:
b = np.array([True,True,False,False,False])  # shape 이 같아야한다.!!!!!!!!!!!!!!!!!
b.shape

(5,)

In [6]:
a[b]

array([1, 2])

In [8]:
a

array([1, 2, 3, 4, 5])

In [7]:
a[[False,True,False,True,False]]   # True 인 index 의 값만 반환해준다.// 리스트로 넣어도 되고 / b처럼 배열로 만들어서 넣어도된다.

array([2, 4])

In [9]:
##### 블리언 indexing을 왜 하나
# - 원하는 조건의 값을 찾으려고 한다.

# - 벡터화 (연산)
# 배열 + 배열 : 같은 인덱스의 원소끼리 연산.
# 배열 + scalar :배열의 모든 원소들과 scalar 를 연산 
a = np.array([1,2,3])
b = np.array([10,20,30])
a+b

array([11, 22, 33])

In [10]:
a+ 20

array([21, 22, 23])

In [12]:
a > 2   # 비교연산 a 의 각각의 값과 크기를 비교한다.

array([False, False,  True])

In [48]:
arr = np.arange(100)
np.random.shuffle(arr)
arr

array([28, 91, 86, 10, 74, 90, 20, 17, 36, 60, 95, 79,  3,  9, 93, 59, 29,
       26, 37, 16, 48, 14, 50, 25, 30, 13, 41, 70, 11, 98, 18, 73, 89,  2,
       69, 32, 88, 78, 23, 65, 71, 68, 39,  0,  7, 35,  6, 75, 33, 43, 66,
       99, 55, 77, 94, 62, 96, 52, 38, 57,  4, 46, 44, 45, 83, 27, 56, 19,
       84,  5, 51, 40, 72, 47, 63, 22,  1, 31, 58, 67, 49, 42, 54, 12, 64,
       82, 24,  8, 61, 80, 87, 85, 92, 97, 34, 15, 21, 81, 76, 53])

In [130]:
##----------------------- 연습

In [49]:
k= np.arange(50)
np.random.shuffle(k)

k

array([40, 42, 30, 10, 45, 23, 14, 41, 18, 46, 19, 12, 32,  8, 11,  3,  4,
       31, 43, 38, 26, 37, 27, 48, 20, 13, 22, 25, 39, 15, 28, 33, 36, 47,
        1, 17,  5,  0,  6, 16, 49, 29,  2,  9, 35, 34,  7, 24, 44, 21])

In [129]:
k1=k[k<=20]
np.sort(k1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [17]:
# arr 의 원소중에서 50 이상인 값들만 조회
arr[arr >= 50]

array([60, 94, 71, 53, 61, 97, 65, 90, 74, 58, 51, 82, 89, 54, 83, 68, 66,
       93, 50, 63, 52, 78, 92, 81, 69, 75, 91, 84, 62, 76, 72, 70, 59, 95,
       99, 56, 64, 57, 88, 73, 98, 80, 85, 67, 55, 96, 79, 87, 86, 77])

In [62]:
arr2 = np.arange(100).reshape(2,50)
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98, 99]])

In [63]:
arr2 >=50   # 같은 shape

array([[False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True]])

In [64]:
arr2[arr2 >=50]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [21]:
arr2[arr2 >=30]      # 결과가 True 인것만 1차원 배열로 보여준다.

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,
       81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
       98, 99])

In [23]:
True and False , True & False

(False, False)

In [26]:
not True,

(False,)

In [29]:
# arr 20 ~30  
arr[(arr >= 20)& (arr<=30)]   #넘파이에서 and 연산자 안되고 기호 & 넣어줘야함 // or 도 마찬가지 

array([29, 27, 26, 28, 25, 23, 22, 21, 30, 20, 24])

In [31]:
# arr 50 보다 크지않은 값들
#arr < 50
#not (arr <50)   # not대신 ~ 을 써야함 // 파이썬은 not
arr[~(arr <50)]

array([60, 94, 71, 53, 61, 97, 65, 90, 74, 58, 51, 82, 89, 54, 83, 68, 66,
       93, 50, 63, 52, 78, 92, 81, 69, 75, 91, 84, 62, 76, 72, 70, 59, 95,
       99, 56, 64, 57, 88, 73, 98, 80, 85, 67, 55, 96, 79, 87, 86, 77])

In [132]:
np.sort(k)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [134]:
k[(k>10) & (k<20)]  # 괄호 꼭 해야한ㄷ.ㅏ.

array([11, 12, 17, 14, 13, 18, 16, 15, 19])

In [137]:
np.sort(k[~(k<10)])

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [51]:
k1 = np.arange(3,40)
np.random.shuffle(k1)

In [54]:
k1

array([36,  5,  7, 21, 22, 14,  9,  4, 38, 39, 15, 29, 30, 18, 20, 19, 37,
       32, 34, 17, 31, 27,  8, 26, 23, 33,  3, 24, 13, 25, 16, 11,  6, 28,
       10, 35, 12])

In [56]:
k2=np.sort(k1)

In [57]:
np.sort(k2[~(k2<15)])

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39])

## 넘파이에서 논리연산자 
- 파이썬 비교 연산자인 and,or,not 을 사용 못함
- `&` = and
- `|`  = or
- `~`  =not
- 피연산자들을 ( )로 묶어야한다.

In [138]:
k

array([46, 11, 12,  8, 29, 41,  0, 28, 21, 31, 17, 14, 39, 36,  6, 22, 40,
       27, 20,  4,  3, 32, 13, 49, 10, 37, 45, 23, 30, 44,  9, 38, 18, 26,
       33, 35,  7,  1, 47, 48, 42,  5, 43, 16, 34, 24,  2, 15, 19, 25])

In [141]:
np.sort(k[(k<40) | (k<30)]) # 40 보다 작은것만 있을듯 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

### np.where()
- np.where(boolean 배열) - True인 index를 반환
- boolean연산과 같이쓰면 특정 조건을 만족하는 원소의 index조회됨.
- np.where(booean 배열, True를 대체할 값, False를 대체할 값)  -- 블리언 배열에 대해 True ,False

    - True와 False를 다른 값으로 변경한다.

In [35]:
a = np.array([True,False,True])
r = np. where(a)  # true인 index들 를 튜플안에 ndarray에 담아서 반환
print(type(r))
print(r[0])

<class 'tuple'>
[0 2]


# where 를 왜쓰나  
- 조건에 만족하는 원소가 몇번 인덱스 인지를 알고 싶다.// boolean indexing은 index의 값을 반환하지만 where는 인덱스번호 를 반환

In [148]:
k=np.arange(50)
d=np.random.permutation(k)
d

array([44, 39, 48, 22,  0, 29, 40, 30, 20, 11, 17,  5, 47, 34, 10, 42, 38,
       15,  1, 32,  9, 43, 25, 41, 46, 12, 36, 49, 26,  8,  2, 23,  7, 31,
       14, 28, 13, 33, 19, 24, 27, 18, 21,  3, 16,  4,  6, 35, 45, 37])

In [151]:
np.where(d>30,'30보다 큼',d)  # True, False 두가지 중에 하나만 할거면 빈상태로 두는게 아니라 배열 이름으로 채워줘야함 

array(['30보다 큼', '30보다 큼', '30보다 큼', '22', '0', '29', '30보다 큼', '30',
       '20', '11', '17', '5', '30보다 큼', '30보다 큼', '10', '30보다 큼',
       '30보다 큼', '15', '1', '30보다 큼', '9', '30보다 큼', '25', '30보다 큼',
       '30보다 큼', '12', '30보다 큼', '30보다 큼', '26', '8', '2', '23', '7',
       '30보다 큼', '14', '28', '13', '30보다 큼', '19', '24', '27', '18', '21',
       '3', '16', '4', '6', '30보다 큼', '30보다 큼', '30보다 큼'], dtype='<U11')

In [36]:
# 50 이상인 값들의 <<index번호를 반환>>를 조회
np.where(arr>=50)

(array([ 0,  1,  2,  3,  4,  5,  7,  8, 10, 13, 14, 16, 19, 20, 21, 22, 25,
        27, 29, 34, 40, 41, 42, 44, 45, 46, 48, 50, 52, 56, 58, 60, 62, 64,
        66, 67, 69, 70, 77, 78, 80, 83, 85, 88, 89, 92, 93, 95, 96, 98],
       dtype=int64),)

In [40]:
np.where(a,'참','거짓')  # TRUE s는 참  FAlse 거짓으로 변경된 새로운 ndarray 배열 객체를 반환

array(['참', '거짓', '참'], dtype='<U2')

In [42]:
np.where(arr>=50, "50이상", "50 미만")

array(['50이상', '50이상', '50이상', '50이상', '50이상', '50이상', '50 미만', '50이상',
       '50이상', '50 미만', '50이상', '50 미만', '50 미만', '50이상', '50이상', '50 미만',
       '50이상', '50 미만', '50 미만', '50이상', '50이상', '50이상', '50이상', '50 미만',
       '50 미만', '50이상', '50 미만', '50이상', '50 미만', '50이상', '50 미만',
       '50 미만', '50 미만', '50 미만', '50이상', '50 미만', '50 미만', '50 미만',
       '50 미만', '50 미만', '50이상', '50이상', '50이상', '50 미만', '50이상', '50이상',
       '50이상', '50 미만', '50이상', '50 미만', '50이상', '50 미만', '50이상', '50 미만',
       '50 미만', '50 미만', '50이상', '50 미만', '50이상', '50 미만', '50이상',
       '50 미만', '50이상', '50 미만', '50이상', '50 미만', '50이상', '50이상', '50 미만',
       '50이상', '50이상', '50 미만', '50 미만', '50 미만', '50 미만', '50 미만',
       '50 미만', '50이상', '50이상', '50 미만', '50이상', '50 미만', '50 미만', '50이상',
       '50 미만', '50이상', '50 미만', '50 미만', '50이상', '50이상', '50 미만',
       '50 미만', '50이상', '50이상', '50 미만', '50이상', '50이상', '50 미만', '50이상',
       '50 미만'], dtype='<U5')

In [43]:
# 50 이상인 값은 " 50 이상"으로 변경하고 50미만인 값은 그대로 나오도록 
np.where(arr>=50,"50이상",arr)   # 50이상이 문자열이라 다 문자열로 바뀜

array(['50이상', '50이상', '50이상', '50이상', '50이상', '50이상', '29', '50이상',
       '50이상', '27', '50이상', '35', '37', '50이상', '50이상', '46', '50이상',
       '41', '39', '50이상', '50이상', '50이상', '50이상', '26', '1', '50이상', '0',
       '50이상', '28', '50이상', '49', '25', '40', '23', '50이상', '19', '48',
       '38', '43', '2', '50이상', '50이상', '50이상', '6', '50이상', '50이상',
       '50이상', '4', '50이상', '34', '50이상', '10', '50이상', '9', '22', '36',
       '50이상', '3', '50이상', '17', '50이상', '47', '50이상', '15', '50이상', '8',
       '50이상', '50이상', '42', '50이상', '50이상', '5', '12', '21', '30', '14',
       '33', '50이상', '50이상', '16', '50이상', '20', '44', '50이상', '7',
       '50이상', '32', '24', '50이상', '50이상', '18', '45', '50이상', '50이상',
       '11', '50이상', '50이상', '13', '50이상', '31'], dtype='<U11')

In [152]:
#0= 흑 ,1 =백
k= np.random.choice([0,1],size=30)
np.where(k==0,'흑','백')

array(['흑', '흑', '백', '백', '흑', '흑', '흑', '흑', '흑', '백', '백', '흑', '백',
       '흑', '백', '백', '백', '백', '흑', '흑', '백', '흑', '백', '백', '백', '흑',
       '흑', '백', '흑', '백'], dtype='<U1')

In [153]:
np.where(k==0) # k==0 인 원소의 인덱스 

(array([ 0,  1,  4,  5,  6,  7,  8, 11, 13, 18, 19, 21, 25, 26, 28],
       dtype=int64),)

In [44]:
# 0여성 1남성
gender = np.random.choice([0,1],size = 20)
gender

array([0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [51]:
# np.where(gender=0,1'여성','남성')   ---> 내가 한거 틀림

np.where(gender ==0,"여성","남성")  # 블리언 의결과 True 인것 "여성", False "남성"

array(['여성', '남성', '남성', '여성', '여성', '남성', '여성', '여성', '남성', '여성', '여성',
       '여성', '여성', '여성', '여성', '여성', '여성', '여성', '여성', '여성'], dtype='<U2')

In [65]:
np.where(gender ==0)  # index number 만 반환

(array([ 0,  3,  4,  6,  7,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       dtype=int64),)

- 2차원도 마찬가지   (n차원도 마찬가지)
    - 단 where는 ""축""별로 배열이 반환된다. [0,1], [2,3] => (0,2)  (1,3)
    - 보통 Vector에 적용한다.

In [157]:
arr2 = [
    [1,10,7],
    [4,2,10],
    [10,2,8]
]
arr2= np.array(arr2)
arr2

array([[ 1, 10,  7],
       [ 4,  2, 10],
       [10,  2,  8]])

In [164]:
print(arr2[arr2>=5])

[10  7 10 10  8]


In [166]:
print(np.where(arr2>=5,'5이상',arr2))

[['1' '5이상' '5이상']
 ['4' '2' '5이상']
 ['5이상' '2' '5이상']]


In [167]:
print(arr2>=4)

[[False  True  True]
 [ True False  True]
 [ True False  True]]


In [59]:
r = np.where(arr2>=5)
print(type(r))
r  # 밑에 튜플 (0번축 인덱스들,1번축 인덱스들 )
#(0,1),(0,2),(1,2),(2,0),(2,2)

<class 'tuple'>


(array([0, 0, 1, 2, 2], dtype=int64), array([1, 2, 2, 0, 2], dtype=int64))

In [56]:
arr2>=5

array([[False,  True,  True],
       [False, False,  True],
       [ True, False,  True]])

In [60]:
np.where(arr2>=5,'크다','작다')

array([['작다', '크다', '크다'],
       ['작다', '작다', '크다'],
       ['크다', '작다', '크다']], dtype='<U2')

### 기타
- np.any(boolean 배열)
    - 배열에 True가 하나라도 있으면 True 반환
- np.all(boolean 배열)
    - 배열의 모든 원소가 True이면 True 반환

In [66]:
np.any([False,False,False])

False

In [67]:
np.any([True,False,False])

True

In [68]:
np.all([True,True,True])

True

In [69]:
np.all([True,False,True])

False

In [70]:
arr

array([60, 94, 71, 53, 61, 97, 29, 65, 90, 27, 74, 35, 37, 58, 51, 46, 82,
       41, 39, 89, 54, 83, 68, 26,  1, 66,  0, 93, 28, 50, 49, 25, 40, 23,
       63, 19, 48, 38, 43,  2, 52, 78, 92,  6, 81, 69, 75,  4, 91, 34, 84,
       10, 62,  9, 22, 36, 76,  3, 72, 17, 70, 47, 59, 15, 95,  8, 99, 56,
       42, 64, 57,  5, 12, 21, 30, 14, 33, 88, 73, 16, 98, 20, 44, 80,  7,
       85, 32, 24, 67, 55, 18, 45, 96, 79, 11, 87, 86, 13, 77, 31])

In [71]:
np.any(arr>50)   # arr안에 50 초과인 값이 1개라도 있는지 ???

True

In [72]:
np.all(arr>50)   # arr안의 모든 값이 50 초과 인지??

False

In [171]:
d3 = np.arange(30).reshape(2,3,5)
d3

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [172]:
np.any(d3>20)

True

In [174]:
np.all(d3>-1)

True

In [180]:
np.sum(d3>20)

9

In [74]:
#50 초과인 값이 몇개?
np.sum(arr>50)  # 블리언이라 arr>50 의 결과는 True하고 False 만 나온다. 그래서 1,0으로 처리후 계산 하는것이다.~!
# sum() : 배열내 원소의 총합계. boolean 배열 --> True :1 ,False:0 으로 처리후 계산 즉, True의 개수 이다~~!

49

In [75]:
arr>50  

array([ True,  True,  True,  True,  True,  True, False,  True,  True,
       False,  True, False, False,  True,  True, False,  True, False,
       False,  True,  True,  True,  True, False, False,  True, False,
        True, False, False, False, False, False, False,  True, False,
       False, False, False, False,  True,  True,  True, False,  True,
        True,  True, False,  True, False,  True, False,  True, False,
       False, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True,  True, False,  True,  True, False,
       False, False, False, False, False,  True,  True, False,  True,
       False, False,  True, False,  True, False, False,  True,  True,
       False, False,  True,  True, False,  True,  True, False,  True,
       False])

### 정렬
- np.sort(arr)/ ndarray.sort() : arr을 정렬
 - np.sort(배열) : 배열을 정렬한 결과를 가진 새로운 배열을 반환(카피본), 원본 안바뀜
 - 배열.sort() : 원본 배열을 정렬.
 
- np.argsort(arr): 정렬 후 index를 반환 ( 정렬한 결과에 대한 )
-  (여기있는거 다)오름차순 정렬만 지원. 내림차순을 할 경우 정렬 후 reverse 해야한다.

In [209]:
k=np.arange(100)
np.random.shuffle(k)
print(k)
print(k.shape)

[73 34 72  1 27 79 66 57 80 36 70 82 46 21 97 76 44 18  6 75 17 62 78 32
 38 23 35  4 55 45 65 48  7 10 30 90 94 84 42 49 74 29 71  8 47 31 91 41
 88 58 54 22 68 83 93 16 26 11 61 15  3 59 43  9 87 50 40 99 14 52 89 37
 12 81 28 19 24 95 64 60 67  0 77 85 39 25 86 53 63 56  5 33 98 96  2 20
 51 92 69 13]
(100,)


In [205]:
np.sort(k) # 카피본 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [207]:
k.sort()
print(k)  # 원본 바뀜

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [208]:
k[::-1]  # 내림차순을 하고 싶다면 정렬후 reverse

array([99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83,
       82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66,
       65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49,
       48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [211]:
k.sort()[::-1]

TypeError: 'NoneType' object is not subscriptable

In [212]:
np.sort(k)[::-1]

array([99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83,
       82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66,
       65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49,
       48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [186]:
np.sort(arr)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [187]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [78]:
x = np.sort(arr)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [79]:
arr  # 원본 그대로 

array([60, 94, 71, 53, 61, 97, 29, 65, 90, 27, 74, 35, 37, 58, 51, 46, 82,
       41, 39, 89, 54, 83, 68, 26,  1, 66,  0, 93, 28, 50, 49, 25, 40, 23,
       63, 19, 48, 38, 43,  2, 52, 78, 92,  6, 81, 69, 75,  4, 91, 34, 84,
       10, 62,  9, 22, 36, 76,  3, 72, 17, 70, 47, 59, 15, 95,  8, 99, 56,
       42, 64, 57,  5, 12, 21, 30, 14, 33, 88, 73, 16, 98, 20, 44, 80,  7,
       85, 32, 24, 67, 55, 18, 45, 96, 79, 11, 87, 86, 13, 77, 31])

In [82]:
y= arr.sort()
print(y)  # 반환값이 없음 why? 원본을 바꾼것 이기때문에 따로 반환할게 없다.

None


In [83]:
arr  # 원본 정렬됨

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [84]:
arr[::-1]   # 내림 차순 정렬을 하고 싶으면 정렬후에 -1로 뒤집어야함

array([99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83,
       82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66,
       65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49,
       48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [183]:
#내림차순
a = np.array([3,1,2,5])
a

array([3, 1, 2, 5])

In [184]:
np.sort(a)[::-1]  # 내림 차순 정렬  // 내림차순하는 함수가 따로 없고 -1로 reverse 해야한다.

array([5, 3, 2, 1])

In [185]:
a.sort()[::-1]

TypeError: 'NoneType' object is not subscriptable

In [89]:
np.argsort(a)  # 정렬하기전 원소의 인덱스번호를 이용하여 정렬할때 몇번째로 옮겨갔는지 알려준다.
                # b

array([1, 2, 0, 3], dtype=int64)

In [90]:
np.sort(a)

array([1, 2, 3, 5])

In [91]:
#내림 차순
np.argsort(a)[::-1]  # 정렬후 index

array([3, 0, 2, 1], dtype=int64)

In [94]:
a[np.argsort(a)[::-1]]

array([5, 3, 2, 1])

In [95]:
a[np.argsort(a)]

array([1, 2, 3, 5])

In [227]:
d = np.arange(5)
np.random.shuffle(d) # 원본 섞기 
print(d1)

None


In [230]:
d

array([0, 2, 3, 4, 1])

In [229]:
d.argsort()

array([0, 4, 1, 2, 3], dtype=int64)

In [232]:
np.argsort(d)

array([0, 4, 1, 2, 3], dtype=int64)

In [233]:
d

array([0, 2, 3, 4, 1])

In [ ]:
## 2 차원배열

In [96]:
l = [
    [3,1,5],
    [1,2,9],
    [10,20,5]
]
b= np.array(l)
b

array([[ 3,  1,  5],
       [ 1,  2,  9],
       [10, 20,  5]])

In [258]:
np.sort(b)

array([[ 1,  3,  5],
       [ 1,  2,  9],
       [ 5, 10, 20]])

In [259]:
np.sort(b,axis=0)

array([[ 1,  2,  5],
       [ 1,  3,  9],
       [ 5, 10, 20]])

In [260]:
b.sort()

In [261]:
b

array([[ 1,  3,  5],
       [ 1,  2,  9],
       [ 5, 10, 20]])

In [97]:
np.sort(b)  # 카피본//# 다차원 배열 정렬에서 axis를 생략하면 마지막 축을 기준으로 정렬. (3차원일때는 2번축 기준)

array([[ 1,  3,  5],
       [ 1,  2,  9],
       [ 5, 10, 20]])

In [99]:
b

array([[ 3,  1,  5],
       [ 1,  2,  9],
       [10, 20,  5]])

In [98]:
np.sort(b,axis = 0)  #  0 번축 기준으로 정렬 (세로).

array([[ 1,  1,  5],
       [ 3,  2,  5],
       [10, 20,  9]])

In [100]:
np.sort(b,axis=1)  # 1번축 기준으로 정렬.

array([[ 1,  3,  5],
       [ 1,  2,  9],
       [ 5, 10, 20]])

In [256]:
d = np.arange(15).reshape(3,5)
d


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [257]:
np.random.shuffle(d)
print(d)

[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [ 5  6  7  8  9]]
