### 그림 넣는 법
1. 이미지 주소 복사 markdown 상태에서 // 밑에 문법대로 하면됨~

![alt(이미지 없을때 넣을 문자)](http://localhost:8888/notebooks/Daemin_Kim(python)/Numpy/02_Numpy_indexing_slicing.ipynb)
![호랑이](img/t.jpg) 

캡처한거 복사하고 바로 paste 하면 바로 이미지넣어줌 
그림판 잘라내기도 잘라낸다음 복사 붙여넣기 하면됨

# url 넣을때 문법

[넘파이 2](http://localhost:8888/notebooks/Daemin_Kim(python)/Numpy/02_Numpy_indexing_slicing.ipynb)

# 배열의 형태(shape) 변경

## reshape()을 이용한 차원 변경
- `numpy.reshape(a(배열), newshape)` 또는 `ndarray.reshape(newshape)` =`a.reshape`
    - a: 형태를 변경할 배열
    - newshape : 변경할 형태 설정. 
 ### <<<<<<<<<<<**원소의 개수를 유지하는 shape으로만 변환 가능하다.**>>>>>>>>>>>>>>>>>>>
    - 원래 배열 사이즈와 reshape 하는 배열의 사이즈는 같아야한다!!
    - 두가지 방법 다 원본 배열을 변경시키지 않는다.(shape을 바꾼 새로운 배열(카피본)을 반환)  두가지 방법다

In [1]:
import numpy as np

In [190]:
a= np.arange(20)
print(a.shape)
print(a.size)
a

(20,)
20


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [191]:
a.reshape(2,2,5)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [8]:
b= np.reshape(a, (4,5)) # 함수 이용방법
print(b.shape,b.size)
print(b)

(4, 5) 20
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [9]:
a  # 원본 그대로임

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [15]:
c = a.reshape((4,5))  # 객체지향적 방법
print(c.shape)
print(c.size)
c

(4, 5)
20


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [16]:
a # 원본그대로 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [18]:
d = a.reshape(4,5)  # 괄호 없이 줘도 됨
d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [21]:
e = a.reshape(2,2,5)
print(e.size)  # shape 은 다르지만 size 동일 
print(e.shape)
e

20
(2, 2, 5)


array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [22]:
np.reshape(a,(3,3))  # a 의 size = 20 인데 -> reshape.size 9 원본가 사이즈가 다르면 error 발생

ValueError: cannot reshape array of size 20 into shape (3,3)

In [194]:
k = np.arange(10)
k

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [196]:
np.reshape(k,(2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [25]:
f= np.arange(5*5*5).reshape(5,5,5)
g= np.arange(3*2*7).reshape(3,2,7)


In [197]:
f

array([[[  0,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14],
        [ 15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24]],

       [[ 25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34],
        [ 35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44],
        [ 45,  46,  47,  48,  49]],

       [[ 50,  51,  52,  53,  54],
        [ 55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64],
        [ 65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74]],

       [[ 75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84],
        [ 85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94],
        [ 95,  96,  97,  98,  99]],

       [[100, 101, 102, 103, 104],
        [105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114],
        [115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124]]])

In [198]:
np.reshape(f,-1)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124])

In [201]:
np.reshape(f,(5,-1))  # -1이 축에 들어가면 알아서 계산해서 size를 설정해준다.

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,
         38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
         63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74],
       [ 75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,
         88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
        113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124]])

In [26]:
print(f.shape,g.shape)

(5, 5, 5) (3, 2, 7)


In [28]:
#f -> 1차원 배열로 바꾸고 싶을때 
f_1=np.reshape(f,125)  # newshape 에 정수를 넣으면 1차원 배열로 변환
print(f_1.shape)
f_1

(125,)


array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124])

- newshape을 지정할 때 특정 축에 -1을 주면 원소수에 맞춰서 size를 정한다.(전체 축중에 하나만 사용가능하다)

In [29]:
f_2 = np.reshape(f,-1)  # 
print(f_2.shape)
f_2

(125,)


array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124])

In [30]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [33]:
a_1=np.reshape(a,(5,-1))     # 원본에 맞게 0axis = 5 일때   1axis를 맞춰서 사이즈 동일하게 해라 
print(a_1.shape)
a_1

(5, 4)


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [35]:
a_2 = a.reshape(2,2,-1)   # -1은 다하고 마지막 하나에만 쓸 수 ㅇㅣㅆ다.
print(a_2.shape)
a_2

(2, 2, 5)


array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [36]:
np.reshape(a_2, -1) # 1차원 만들어 달라고!  size맞춰서 바뀜

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [202]:
k= np.arange(100).reshape(2,10,5)
k

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74],
        [75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]]])

In [204]:
b=k.reshape(5,5,-1)
b.shape


(5, 5, 4)

## 차원 늘리기(확장)

### numpy.newaxis 속성을 이용해 차원 늘리기
- size가 1인 축 (axis)를 늘릴때 사용한다. 
    - **지정한 axis에 size 1인 축을 추가한다.**
- slicing에 사용하거나 indexing에 `...`과 같이 사용한다.
    - slicing의 경우 원하는 위치의 축을 늘릴 수 있다.
    - index에 ...과 사용하는 경우 첫번째나 마지막 축을 늘릴때 사용한다.
    

In [37]:
import numpy as np

In [208]:
k = np.arange(9)
print(k.shape)
print(k)
k[:]

(9,)
[0 1 2 3 4 5 6 7 8]


array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [207]:
# (5,)  --> (1,5)
d=k[np.newaxis,:]
d

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [210]:
# (5,) ---> y :(5,1)
d=k[:,np.newaxis]
d

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [ ]:
# a : (5,) ㅠ --> z: (1,5,1)

In [17]:
c = a[np.newaxis,:,np.newaxis]
c.shape

(1, 5, 1)

In [16]:
c

array([[[1],
        [2],
        [3],
        [4],
        [5]]])

In [11]:
a

array([1, 2, 3, 4, 5])

In [212]:
d = k[np.newaxis,:,np.newaxis]
d

array([[[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8]]])

In [4]:
import numpy as np

In [5]:
a=np.arange(1,6)
print(a.shape)
print(a)

(5,)
[1 2 3 4 5]


In [40]:
# (5,)  --> (1,5)로 만들고 싶을때/  어차피 사이즈는 동일하다 축이 1일때
a[:]

array([1, 2, 3, 4, 5])

In [41]:
x=a[np.newaxis, :]  # 0번축을 만든다
print(x.shape)
x

(1, 5)


array([[1, 2, 3, 4, 5]])

In [42]:
a # 원본 동일

array([1, 2, 3, 4, 5])

In [43]:
# (5,) ---> y :(5,1)
y = a[:, np.newaxis]  #0 번축 : , -->슬라이싱 하고 , 1번축 np.newaxis
print(y.shape)
y

(5, 1)


array([[1],
       [2],
       [3],
       [4],
       [5]])

In [48]:
# a : (5,)  --> z: (1,5,1)

z = a[np.newaxis, : ,np.newaxis]  # 0번축 2번축을 만들어 냈다. // np.newaxis 를 계속넣으면 축을 계속 만들 수 잇따.
print(z.shape)
z

(1, 5, 1)


array([[[1],
        [2],
        [3],
        [4],
        [5]]])

In [49]:
b= np.arange(6).reshape(2,3)
print(b.shape)
b

(2, 3)


array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
--------------------------------------------------

In [214]:
b= np.arange(6).reshape(2,3)
print(b)
print(b.shape)

[[0 1 2]
 [3 4 5]]
(2, 3)


In [226]:
# b:(2,3)  --> m=(1,2,3)

k=b[np.newaxis, : ,:]
print(k.shape)
print(k)


(1, 2, 3)
[[[0 1 2]
  [3 4 5]]]


In [229]:
# b:(2,3)  --> n=(2,3,1)

k= b[:,:,np.newaxis]
k.shape
k

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [230]:
b

array([[0, 1, 2],
       [3, 4, 5]])

In [235]:
# (2,3) --> (2,1,3,1)
k = b[ 0:2 ,np.newaxis,0 :4 ,np.newaxis]

k.shape

(2, 1, 3, 1)

In [ ]:
# b:(2,3)  --> n=(2,3,1)

In [237]:
k = b[: , : , np.newaxis]
k

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [51]:
# b:(2,3)  --> m=(1,2,3)  // 대부분 앞이나 뒤에 축을 늘린다.
m = b[np.newaxis, :, :]
print(m.shape)
m

(1, 2, 3)


array([[[0, 1, 2],
        [3, 4, 5]]])

In [52]:
# b:(2,3)  --> n=(2,3,1)
n = b[:,:,np.newaxis]
print(n.shape)
n

(2, 3, 1)


array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [54]:
# (2,3) --> (2,1,3,1)
o = b[:,np.newaxis, :, np.newaxis]  
print(o.shape)
o

(2, 1, 3, 1)


array([[[[0],
         [1],
         [2]]],


       [[[3],
         [4],
         [5]]]])

In [ ]:
# b:(2,3)  --> n=(2,3,1)
n = b[:,:,np.newaxis]
print(n.shape)
n

In [61]:
# b:(2,3)  --> n=(2,3,1)  // 이미지 처리할 때 많이 씀
np.reshape(b,(2,3,1))

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

### indexing에 ... 과 같이 사용
- ndarray[..., np.newaxis]
- 첫번째 축이나 마지막 축을 늘릴때만!!!! 사용가능

In [ ]:
(2,3,4)  -> (1,2,3,4)
         ->(2,3,4,1)

In [57]:
# b :(2,3)  -> b2: (1,2,3)
b2 = b[np.newaxis,...]
print(b2.shape)
b2

(1, 2, 3)


array([[[0, 1, 2],
        [3, 4, 5]]])

In [58]:
# b :(2,3)  -> b2: (2,3,1)
b3 = b[...,np.newaxis]
print(b3.shape)
b3

(2, 3, 1)


array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [240]:
b.shape

(2, 3)

In [243]:
k=b[...,np.newaxis]
k.shape

(2, 3, 1)

In [244]:
k=b[np.newaxis,...]
k.shape

(1, 2, 3)

### numpy.expand_dims (배열, axis)
- 매개변수로 받은 배열에 지정한 axis의 rank를 확장한다.
- y = a[:, np.newaxis] 이거랑 원리는 같은데 함수 버전이라고 생각하면 된다.

In [62]:
print(a.shape)
a

(5,)


array([1, 2, 3, 4, 5])

In [247]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [248]:
np.expand_dims(a,axis=1).shape

(20, 1)

In [249]:
np.expand_dims(a,axis=0).shape

(1, 20)

In [18]:
a

array([1, 2, 3, 4, 5])

In [21]:
np.expand_dims(a,axis= 1).shape

(5, 1)

In [22]:
np.expand_dims(a,axis=0).shape

(1, 5)

In [65]:
# (5,)->(5,1)

a1= np.expand_dims(a, axis=1)
print(a1.shape)
#a1

(5, 1)


In [66]:
# (5,)  

a2 = np.expand_dims(a, axis=0)
print(a2.shape)

(1, 5)


In [67]:
b.shape

(2, 3)

In [68]:
#(2, 3)  --> (2,1,3)

b2 = np.expand_dims(b, axis=1)
b2.shape

(2, 1, 3)

## 차원 줄이기(축소)

### numpy.squeeze(배열, axis=None), 배열객체.squeeze(axis=None)
- 배열에서 지정한 축(axis)을 제거하여 차원(rank)를 줄인다.
- <<<<<<<<<<<<<<<<<**제거하려는 축의 size는 1이어야 한다.**>>>>>>>>>>>>>>>>>>> size 유지를 위해서 // size 는 절대 바뀌면안된다.
- 축을 지정하지 않으면 size가 1인 모든 축을 제거한다.
    - (3,1,1,2) => (3,2)

In [250]:
a = np.arange(12).reshape(1,2,1,2,3,1)
print(a.shape)

(1, 2, 1, 2, 3, 1)


In [251]:
b= np.squeeze(a)    # 축이 1인것을 다 삭제 /  중간에 1이 있어도 삭제 한다.
print(b.shape)

(2, 2, 3)


In [252]:
c=a.squeeze()
print(c.shape)

(2, 2, 3)


In [76]:
c = np.squeeze(a, axis = 2)  # 원하는 축만 삭제 
print(c.shape)

(1, 2, 2, 3, 1)


In [79]:
d = np.squeeze(a, axis = 1)  # size 가 1이 아닌축은 제거가 안되고 error

ValueError: cannot select an axis to squeeze out which has size not equal to one

In [253]:
k= np.arange(18).reshape(2,1,3,3,1)
k.shape

(2, 1, 3, 3, 1)

In [254]:
d=k.squeeze()  # axis 를 정해주지 않아서 1인 axis를 다 삭제 
d.shape  

(2, 3, 3)

In [256]:
m=np.squeeze(k,axis=4)  #axis를 4로 정해줘서 4번축만 삭제 // 삭제 추가할때는 무조건 size가 1인 축만 할 수있다. 총 size 는 변하면 안되니까.
m.shape

(2, 1, 3, 3)

### 배열객체.flatten()
- 다차원 배열을 1차원으로 만든다.

In [83]:
# (2,3)  ---> (6,)
# (2,2,2,3) ---> (24,)
a = np.arange(20).reshape(2,2,5)
print(a.shape)
a

(2, 2, 5)


array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [258]:
k.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [262]:
d=k.reshape(2,3,3)
d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [264]:
d.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [84]:
a2 = a.flatten()
print(a2)
print(a2.shape)    # 원본은 그대로 있고 //   축순서대로 쭉 넣는다.

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
(20,)


In [25]:
r = np.arange(10).reshape(2,5)
r

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [24]:
r.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## numpy.append(), numpy.insert(), numpy.delete()
- ### append(배열, 추가할값, axis=None)
    - 배열의 **마지막 index**에 추가할값을 추가
    - axis : 축 지정
        - None(기본값) : flatten 한 뒤 추가한다.// 축을 미지정시 flatten 하고 뒤에 추가한다.
- ### insert(배열, index, 추가할값, axis=None)
    - 배열의 index에 추가할값을 추가.  **삽입 원하는 위치에**
    - axis : 축 지정
        - None(기본값) : flatten 한 뒤 삽입한다.
- ### delete(배열, 삭제할index, axis=None)  
    - 배열의 삭제할index의 값들을 삭제한다.
    - 삭제할 index는 index 또는 slice
    - axis : 축 지정
        - None(기본값) : flatten 한 뒤 삭제한다.

### append()

- ### append(배열, 추가할값, axis=None)
    - 배열의 **마지막 index**에 추가할값을 추가
    - axis : 축 지정
        - None(기본값) : flatten 한 뒤 추가한다.// 축을 미지정시 flatten 하고 뒤에 추가한다.

In [85]:
import numpy as np

a = np.array([1,2,3])

In [89]:
r= np.append(a,100)  # 1개의 값을 추가 // 원본은 그대로 추가된 세로운 배열 반환
r             

array([  1,   2,   3, 100])

In [91]:
r= np.append(a,[200,300,400])  # 여러개값 추가 할때 list로 묶어서 전달.
r

array([  1,   2,   3, 200, 300, 400])

In [269]:
k = np.arange(5)
k

array([0, 1, 2, 3, 4])

In [270]:
np.append(k,1000)

array([   0,    1,    2,    3,    4, 1000])

In [271]:
np.append(k,[20,30,1818])

array([   0,    1,    2,    3,    4,   20,   30, 1818])

In [28]:
l =[
    [1,1],
    [2,2],
    [3,3]
    
]
b = np.array(l)
print(b.shape)
b

(3, 2)


array([[1, 1],
       [2, 2],
       [3, 3]])

In [29]:
b

array([[1, 1],
       [2, 2],
       [3, 3]])

In [31]:
np.append(b,[[4,4],[5,5]],axis = 0)

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4],
       [5, 5]])

In [32]:
np.append(b,[[1,2],[3,4],[4,5]],axis =1)

array([[1, 1, 1, 2],
       [2, 2, 3, 4],
       [3, 3, 4, 5]])

In [279]:
#세로방향으로 append [18,18]
np.append(b,[[18,18]],axis=0)  # 리스트로 묶어서 넣어줘야함 

array([[ 1,  1],
       [ 2,  2],
       [ 3,  3],
       [18, 18]])

In [285]:
r = np.append(b,[[4,4],[5,5],[6,6]], axis = 1)
r

array([[1, 1, 4, 4],
       [2, 2, 5, 5],
       [3, 3, 6, 6]])

In [286]:
b


array([[1, 1],
       [2, 2],
       [3, 3]])

In [287]:
#가로 방향으로 append
np.append(b,[[1,2],[2,3],[4,5]],axis=1)

array([[1, 1, 1, 2],
       [2, 2, 2, 3],
       [3, 3, 4, 5]])

In [ ]:
# 여러값 세로 append

In [288]:
np.append(b,[[1,2],[2,3],[4,5]],axis=0)

array([[1, 1],
       [2, 2],
       [3, 3],
       [1, 2],
       [2, 3],
       [4, 5]])

In [95]:
r = np.append(b,[[4,4]], axis = 0)   # 붙이는 축 방향의 번호를 넣는다.
r                                    #

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [96]:
r = np.append(b,[[4,4],[5,5],[6,6]], axis = 0)   # 추가할 배열이 2차원이기도 하고 , 추가할 것이 여러개 일경우 하나로 묶어 줘야함 
r

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4],
       [5, 5],
       [6, 6]])

In [266]:
b

array([[1, 1],
       [2, 2],
       [3, 3]])

In [268]:
r = np.append(b,[[1,2], [2,3], [3,4]],axis = 1)
r

array([[1, 1, 1, 2],
       [2, 2, 2, 3],
       [3, 3, 3, 4]])

In [101]:
r= np.append(b, [[4,4,4],[5,5,5],[6,6,6]], axis = 1)
r

array([[1, 1, 4, 4, 4],
       [2, 2, 5, 5, 5],
       [3, 3, 6, 6, 6]])

In [291]:
r= np.append(b, [[4],[5,],[6,]], axis = 1)
print(r.shape)
print(b.shape)

(3, 3)
(3, 2)


In [102]:
np.append(b, [10,20])  # 다차원 배열에서 축을 지정하지 않으면 flatten 후 append

array([ 1,  1,  2,  2,  3,  3, 10, 20])

In [ ]:
# 3차원해보기

In [149]:
k= np.arange(12).reshape(2,2,3)
k

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [150]:
d = np.append(k,[[[1,1,1]],[[2,2,2]]], axis =1)   # 넣을 값을 2개를 1번방향으로 
d                                                  # 들어갈값을 묶고 2차원 모양으로 2개 만들어줘얗ㄴ다.

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 1,  1,  1]],

       [[ 6,  7,  8],
        [ 9, 10, 11],
        [ 2,  2,  2]]])

### insert
- ### insert(배열, index, 추가할값, axis=None)
    - 배열의 index에 추가할값을 추가.  **삽입 원하는 위치에**
    - axis : 축 지정
        - None(기본값) : flatten 한 뒤 삽입한다.

In [280]:
#세로방향으로 append [18,18]
np.append(b,[[18,18]],axis=0)  # 리스트로 묶어서 넣어줘야함 

array([[ 1,  1],
       [ 2,  2],
       [ 3,  3],
       [18, 18]])

In [103]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [105]:
r= np.insert(a,0,100) # 0번 index 에 100 을 삽입
r

array([100,   1,   2,   3])

In [106]:
r = np.insert(a,2,100)
r

array([  1,   2, 100,   3])

In [ ]:
#np.insert(a,10,5)  # a에 10 번인덱스 5 넣는건데 없는 index를 넣으면 index에러 

In [294]:
a

array([[[[[[ 0],
           [ 1],
           [ 2]],

          [[ 3],
           [ 4],
           [ 5]]]],



        [[[[ 6],
           [ 7],
           [ 8]],

          [[ 9],
           [10],
           [11]]]]]])

In [33]:
k= np.arange(10)
k

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
np.insert(k,2,20)

array([ 0,  1, 20,  2,  3,  4,  5,  6,  7,  8,  9])

In [35]:
np.insert(k,9,90)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, 90,  9])

In [36]:
np.insert(k,8,[2,3,4,5,6,7])

array([0, 1, 2, 3, 4, 5, 6, 7, 2, 3, 4, 5, 6, 7, 8, 9])

In [297]:
np.insert(k,1,1000)

array([   0, 1000,    1,    2,    3,    4,    5,    6,    7,    8,    9])

In [298]:
np.append(k,1000)

array([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9, 1000])

In [300]:
np.insert(k,3,[10,20,30])

array([ 0,  1,  2, 10, 20, 30,  3,  4,  5,  6,  7,  8,  9])

In [299]:
np.append(k,[10,20,30])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 20, 30])

In [108]:
r = np.insert(a, 1 ,[10,20,30])
r

array([ 1, 10, 20, 30,  2,  3])

In [307]:
b = np.array([[1,1],[2,2],[3,3]])
print(b)
print(b.shape)

[[1 1]
 [2 2]
 [3 3]]
(3, 2)


In [312]:
np.insert(b,1,[[1,3],[2,3]],axis =0)  #insert 는 넣을 값을 그대로 [1,3]처럼 줘도 되지만 // 여러값 넣을 때는 list로 묶고 

array([[1, 1],
       [1, 3],
       [2, 3],
       [2, 2],
       [3, 3]])

In [313]:
np.insert(b,1,[1,3],axis =0)

array([[1, 1],
       [1, 3],
       [2, 2],
       [3, 3]])

In [310]:
np.append(b,[[1,3]],axis=0)  #append 는 넣을 값을 리스트로 묶어서 줘야한다.

array([[1, 1],
       [2, 2],
       [3, 3],
       [1, 3]])

In [314]:
b

array([[1, 1],
       [2, 2],
       [3, 3]])

In [322]:
b.shape

(3, 2)

In [318]:
np.insert(b,2,[1,2,3],axis =1)  # axis =1 방향으로 넣을 때도 값이 각각 1개씩이라면 그냥 주고 

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [323]:
np.insert(b,1, [[10,20,30],[5,6,7]],axis =1)

array([[ 1, 10,  5,  1],
       [ 2, 20,  6,  2],
       [ 3, 30,  7,  3]])

In [38]:
np.append(b,[[10,5],[20,6],[30,7]],axis =1)

array([[ 1,  1, 10,  5],
       [ 2,  2, 20,  6],
       [ 3,  3, 30,  7]])

In [329]:
b
print(b.shape)

(3, 2)


In [328]:
np.insert(b,1,[[2,3,5],[2,4,5],[3,4,5]],axis =1)  # 

array([[1, 2, 2, 3, 1],
       [2, 3, 4, 4, 2],
       [3, 5, 5, 5, 3]])

In [325]:
np.append(b,[[1,1],[1,2],[1,3]],axis =1)

array([[1, 1, 1, 1],
       [2, 2, 1, 2],
       [3, 3, 1, 3]])

In [116]:
np.insert(b,1,100)    # axis생략 flatten() 뒤에 insert()

array([  1, 100,   1,   2,   2,   3,   3])

In [117]:
b

array([[1, 1],
       [2, 2],
       [3, 3]])

In [118]:
np.insert(b,1,[10,10],axis=0)  # append 는 무조건 다차원에서 2차원 배열로 전달 하는데 insert는 1개 값일때는 [] 이렇게만 넣는다.

array([[ 1,  1],
       [10, 10],
       [ 2,  2],
       [ 3,  3]])

In [119]:
np.insert(b,1,[[10,10],[20,20]],axis=0)  # 여러개 넣을 때는 묶어서 넣어줌!

array([[ 1,  1],
       [10, 10],
       [20, 20],
       [ 2,  2],
       [ 3,  3]])

In [120]:
np.insert(b,2,100,axis =0) # 동일한 값을 넣을 경우 정수로 넣어줘도 된다.

array([[  1,   1],
       [  2,   2],
       [100, 100],
       [  3,   3]])

In [122]:
np.insert(b, 0, [4,5,6] ,axis=1)

array([[4, 1, 1],
       [5, 2, 2],
       [6, 3, 3]])

In [124]:
b

array([[1, 1],
       [2, 2],
       [3, 3]])

In [123]:
np.insert(b,1, [10,20,30],axis =1)

array([[ 1, 10,  1],
       [ 2, 20,  2],
       [ 3, 30,  3]])

In [125]:
np.insert(b,1, [[10,20,30],[5,6,7]],axis =1)

array([[ 1, 10,  5,  1],
       [ 2, 20,  6,  2],
       [ 3, 30,  7,  3]])

In [330]:
b

array([[1, 1],
       [2, 2],
       [3, 3]])

In [335]:
k=np.insert(b,2,[2,3,4], axis=1)
k

array([[1, 1, 2],
       [2, 2, 3],
       [3, 3, 4]])

In [337]:
k = np.insert(b,1,[4,5],axis =0)
k

array([[1, 1],
       [4, 5],
       [2, 2],
       [3, 3]])

In [339]:
k= np.insert(b,2,[[3,4,5],[5,6,7],[7,8,9]], axis =1)
k   # insert axis=1 방향으로 삽입할때는 각각원소에 들어갈 값들을 묶어줘야한다. 각각 원소에 여러개의 값을 넣고 싶으면 그것들을 묶는다.

array([[1, 1, 3, 5, 7],
       [2, 2, 4, 6, 8],
       [3, 3, 5, 7, 9]])

In [340]:
k= np.append(b,[[2,3,4],[3,4,5],[5,6,7]],axis=1)
k

array([[1, 1, 2, 3, 4],
       [2, 2, 3, 4, 5],
       [3, 3, 5, 6, 7]])

In [334]:
k= np.append(b,[[1],[1],[1]] ,axis=1)
k

array([[1, 1, 1],
       [2, 2, 1],
       [3, 3, 1]])

In [ ]:
k= np.append(b,1,[])

### delete

- ### delete(배열, 삭제할index, axis=None)  
    - 배열의 삭제할index의 값들을 삭제한다.
    - 삭제할 index는 index 또는 slice
    - axis : 축 지정
        - None(기본값) : flatten 한 뒤 삭제한다.

In [126]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [128]:
r =  np.delete(a,0)
r  # 원본 그대로 

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [129]:
r = np.delete(a,[2,5,6])
r

array([0, 1, 3, 4, 7, 8, 9])

In [133]:
# slicing 을 이용해서 삭제 
# slicing 을 함수의 매개변수로 전달할 경우 np.s_[slicing]
np.delete(a,np.s_[::2])   #[::2] --> 이게 list 이다 // 'np.s_' 를 붙여줘서 슬라이싱인것을 알려줌

array([1, 3, 5, 7, 9])

In [131]:
#배열[] --> 대괄호 연산자 를 제외한 [] 는 다 리스트 표기 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [342]:
b = np.arange(36).reshape(6,6)
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [343]:
np.delete(b,[0,1], axis =0)

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [344]:
np.delete(b,[0,1], axis =1)

array([[ 2,  3,  4,  5],
       [ 8,  9, 10, 11],
       [14, 15, 16, 17],
       [20, 21, 22, 23],
       [26, 27, 28, 29],
       [32, 33, 34, 35]])

In [345]:
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [137]:
np.delete(b, 0)  # axis 생략 : flatten()후에 delete()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35])

In [346]:
k= np.arange(10)
k

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [347]:
np.delete(k,0)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [348]:
np.delete(k,4)

array([0, 1, 2, 3, 5, 6, 7, 8, 9])

In [355]:
np.delete(k,np.s_[3:6])

array([0, 1, 2, 6, 7, 8, 9])

In [350]:
np.delete(k,np.s_[::3])  #배열 [] : 여기서 []는 연산자 이다. // 나머지는 다 리스트를 뜻하는 것이다. 그래서 numpy 에서 슬라이싱이라는 것을 알려주고 
                        # 작업하려면 np._s[::] 이런식으로 슬라이싱이라는 것을 알려줘야한다.

array([1, 2, 4, 5, 7, 8])

In [351]:
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [353]:
np.delete(b,[-1,-2],axis =0)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [356]:
np.delete(b,np.s_[::2], axis =0)

array([[ 6,  7,  8,  9, 10, 11],
       [18, 19, 20, 21, 22, 23],
       [30, 31, 32, 33, 34, 35]])

In [357]:
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [358]:
np.delete(b,[2,3],axis=1)

array([[ 0,  1,  4,  5],
       [ 6,  7, 10, 11],
       [12, 13, 16, 17],
       [18, 19, 22, 23],
       [24, 25, 28, 29],
       [30, 31, 34, 35]])

In [359]:
np.delete(b,np.s_[::2],axis=1)

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17],
       [19, 21, 23],
       [25, 27, 29],
       [31, 33, 35]])

## 배열 합치기
- ### np.concatenate(합칠 배열리스트, axis=0)
    - 여러 배열을 **축의개수(rank)**를 유지하며 합친다.
    - axis 파라미터 : 축지정
        - 지정된 축을 기준으로 합친다. 
        - default : 0
    - 합치는 배열의 축의 개수(rank) 은 같아야 한다.  ( 같은 차원끼리 합칠수 있다.)
    - axis속성으로 지정한 축 이외의 축의 크기가 같아야 한다.  (지정한 축 방향을 제외한 다른 방향이 같아야 된다고 )
    - 결과의 축의개수(rank)는 대상 배열의 rank와 같다.
        - 1차원끼리 합치면 1차원결과가 나옴
- ### 합칠 대상 배열의 rank가 2일 경우(행렬) 
    - vstack()
    - hstack()
    - np.concatenate()의 간단버전
- ### vstack(합칠배열리스트)
    - 수직으로 쌓는다.
    - concatenate() 의 axis=0 와 동일
    - 합칠 배열들의 열수가 같아야 한다.
- ### hstack(합칠배열리스트)
    - 수평으로 쌓는다.
    - concatenate() 의 axis=1 와 동일
    - 합칠 배열들의 행 수가 같아야 한다.

In [ ]:
# a :(3,2)  b:(3,5)  : axis=1번축으로만 합칠 수있다.  (3,7)
# a: (4,2)  b: (4,2)   : axis = 0 번축 (8,2)  axis = 1번축 (4,4)
# a: (2,3,5) b:(3,1,5)  : 못 합친다.  3차원 2개가 같아야된다.
# a: (2,3,5) b:(7,3,5)  : axis=0 (9,3,5)
            
# 기준 축을 제외한 size는 다 같아야한다.

### concatenate()

- axis=0 이면 0이 늘어난다. 0을 기준으로 합치므로 (그래서 밑으로 (행이 늘어남)붙는다.)
    - 그래서 각 배열의 컬럼 수가 같아야 한다. 
- axis=1 이면 1이 늘어난다. 1을 기준으로 합치므로 (그래서 옆으로 (컬럼이 늘어남) 붙는다.)
    - 그래서 각 배열의 행수가 같아야 한다.

In [39]:
import numpy as np
a = np.array([1,2,3])
b = np.array([10,20,30,40])
c = np.array([100,200])
# 1 차원 배열 합치기 
d = np.concatenate([a,b])
d

array([ 1,  2,  3, 10, 20, 30, 40])

In [41]:
np.concatenate([a,b])

array([ 1,  2,  3, 10, 20, 30, 40])

In [153]:
e = np.concatenate([b,a])
e

array([10, 20, 30, 40,  1,  2,  3])

In [154]:
a  # 원본 그대로 

array([1, 2, 3])

In [155]:
np.concatenate([a,b,c])

array([  1,   2,   3,  10,  20,  30,  40, 100, 200])

In [1]:
import numpy as np
a = np.array([1,2,3])
b = np.array([10,20,30,40])
c = np.array([100,200])

In [ ]:
#1차원 concatenate

In [362]:
np.concatenate((a,b))

array([ 1,  2,  3, 10, 20, 30, 40])

In [363]:
np.concatenate((a,b,c))

array([  1,   2,   3,  10,  20,  30,  40, 100, 200])

In [2]:
x = np.arange(6).reshape(2,3)
y= np.arange(10,16).reshape(2,3)
z = np.arange(20,26).reshape(2,3)
print(x.shape,y.shape,z.shape)

(2, 3) (2, 3) (2, 3)


In [3]:
np.concatenate([x,y],axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15]])

In [4]:
np.concatenate([x,y,z],axis =1)

array([[ 0,  1,  2, 10, 11, 12, 20, 21, 22],
       [ 3,  4,  5, 13, 14, 15, 23, 24, 25]])

In [5]:
c=np.concatenate([x,y,z],axis=0)
c.shape

(6, 3)

In [6]:
print(x)
print(y)
print(z)

[[0 1 2]
 [3 4 5]]
[[10 11 12]
 [13 14 15]]
[[20 21 22]
 [23 24 25]]


In [7]:
k=np.concatenate((x,y))
print(k.shape)  # axis 값을 안주면 axis = 0이다. default =0
print(k)

(4, 3)
[[ 0  1  2]
 [ 3  4  5]
 [10 11 12]
 [13 14 15]]


In [8]:
k=np.concatenate((x,y,z))
print(k.shape)
print(k)

(6, 3)
[[ 0  1  2]
 [ 3  4  5]
 [10 11 12]
 [13 14 15]
 [20 21 22]
 [23 24 25]]


In [9]:
k=np.concatenate([x,y],axis = 1)
print(k.shape)
print(k)

(2, 6)
[[ 0  1  2 10 11 12]
 [ 3  4  5 13 14 15]]


In [10]:
k=np.concatenate([x,y,z],axis =1)
print(k.shape)
print(k)

(2, 9)
[[ 0  1  2 10 11 12 20 21 22]
 [ 3  4  5 13 14 15 23 24 25]]


In [11]:
r= np.concatenate([x,y], axis = 0)
print(r, r.shape)

[[ 0  1  2]
 [ 3  4  5]
 [10 11 12]
 [13 14 15]] (4, 3)


In [12]:
r= np.concatenate([x,y]) #  생략 0 
r

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15]])

In [13]:
r = np.concatenate([x,y],axis=1)
print(r.shape)
print(r)

(2, 6)
[[ 0  1  2 10 11 12]
 [ 3  4  5 13 14 15]]


In [14]:
r= np.concatenate([x,y,z], axis = 1)
print(r.shape)
print(r)

(2, 9)
[[ 0  1  2 10 11 12 20 21 22]
 [ 3  4  5 13 14 15 23 24 25]]


In [15]:
r= np.concatenate([x,y,z], axis = 0)  # (6,3)
r

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15],
       [20, 21, 22],
       [23, 24, 25]])

In [16]:
print(x,x.shape)

[[0 1 2]
 [3 4 5]] (2, 3)


In [17]:
w = np.arange(10).reshape(2,5)
print(w)
print(w.shape)

[[0 1 2 3 4]
 [5 6 7 8 9]]
(2, 5)


In [52]:
np.concatenate([x,w],axis =1)

array([[0, 1, 2, 0, 1, 2, 3, 4],
       [3, 4, 5, 5, 6, 7, 8, 9]])

In [57]:
x.shape

(2, 3)

In [376]:
print(x)
print(x.shape)

[[0 1 2]
 [3 4 5]]
(2, 3)


In [18]:
x

array([[0, 1, 2],
       [3, 4, 5]])

In [19]:
w

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [377]:
k=np.concatenate([x,w],axis =0)  # 기준축 axis를 제외한 다른 축의 size가 같아야하는데 달라서 합치지 못함 

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 5

In [379]:
k=np.concatenate([x,w],axis =1)
print(k.shape)
print(k)

(2, 8)
[[0 1 2 0 1 2 3 4]
 [3 4 5 5 6 7 8 9]]


In [384]:
a = np.arange(12).reshape(2,3,2)
a.shape

(2, 3, 2)

In [385]:
b= np.arange(2*2*7).reshape(2,7,2)
b.shape

(2, 7, 2)

In [386]:
k = np.concatenate([a,b],axis = 1)   # 기준 axis 를 잘보고 나머지 axis 값들이 size가 같은지 확인 하면 합칠 수 있는지 여부를 알 수 있다.
print(k.shape)
print(k)

(2, 10, 2)
[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]
  [10 11]
  [12 13]]

 [[ 6  7]
  [ 8  9]
  [10 11]
  [14 15]
  [16 17]
  [18 19]
  [20 21]
  [22 23]
  [24 25]
  [26 27]]]


In [ ]:
# np.vstack

In [394]:
k1=np.vstack([k,d])
print(k1)
print(k1.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(5, 5)


In [395]:
k2=np.vstack((k,m))
k2

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 5 and the array at index 1 has size 6

In [392]:
k = np.arange(10).reshape(2,5)
print(k.shape)
print(k)

(2, 5)
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [391]:
d= np.arange(15).reshape(3,5)
print(d.shape)
print(d)

(3, 5)
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [390]:
m= np.arange(18).reshape(3,6)
print(m.shape)
print(m)

(3, 6)
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]


In [ ]:
# np.hstack

In [397]:
d1=np.hstack([d,m])
print(d1.shape)
print(d1)

(3, 11)
[[ 0  1  2  3  4  0  1  2  3  4  5]
 [ 5  6  7  8  9  6  7  8  9 10 11]
 [10 11 12 13 14 12 13 14 15 16 17]]


In [168]:
np.concatenate([x,w], axis = 0)   # error

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 5

In [169]:
np.concatenate([x,w], axis = 1) 

array([[0, 1, 2, 0, 1, 2, 3, 4],
       [3, 4, 5, 5, 6, 7, 8, 9]])

In [171]:
a = np.arange(12).reshape(2,2,3)
a.shape

(2, 2, 3)

In [173]:
b= np.arange(2*2*7).reshape(2,2,7)
b.shape

(2, 2, 7)

In [176]:
r = np.concatenate([a,b], axis =2)
print(r.shape)
print(r)

(2, 2, 10)
[[[ 0  1  2  0  1  2  3  4  5  6]
  [ 3  4  5  7  8  9 10 11 12 13]]

 [[ 6  7  8 14 15 16 17 18 19 20]
  [ 9 10 11 21 22 23 24 25 26 27]]]


In [ ]:
# 축에 대한 개념으로 합치는 것을 생각한다.

- ### vstack(합칠배열리스트)
    - 수직으로 쌓는다.
    - concatenate() 의 axis=0 와 동일
    - 합칠 배열들의 열수가 같아야 한다.
- ### hstack(합칠배열리스트)
    - 수평으로 쌓는다.
    - concatenate() 의 axis=1 와 동일
    - 합칠 배열들의 행 수가 같아야 한다.
    
 ** 2차원 배열을 쓸때 **

### vstack()
- 아래에 붙이는 개념이므로 열수가 맞아야 한다. 
- axis=0과 동일   // 2차원에서만 써

In [177]:
np.vstack([x,y])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15]])

In [178]:
np.vstack([x,y,z])  

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15],
       [20, 21, 22],
       [23, 24, 25]])

In [179]:
w.shape

(2, 5)

In [180]:
np.vstack([x,w])  # 1번축이 같아야 된다 /기준이되는 축 0번축을 제외한 축이 같아야하니까

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 5

### hstack()
- 옆으로 붙이는 것이므로 행 수가 같아야 한다.
- axis=1과 동일

In [181]:
np.hstack([x,y,z])  # axis 1 을 기준으로 // 나머지 축의 size 동일 해야한다.

array([[ 0,  1,  2, 10, 11, 12, 20, 21, 22],
       [ 3,  4,  5, 13, 14, 15, 23, 24, 25]])

In [183]:
x.shape, w.shape

((2, 3), (2, 5))

In [182]:
np.hstack([x,w])  

array([[0, 1, 2, 0, 1, 2, 3, 4],
       [3, 4, 5, 5, 6, 7, 8, 9]])

In [184]:
r = np.arange(15).reshape(3,5)

In [187]:
r.shape, x.shape

((3, 5), (2, 3))

In [188]:
np.hstack([x,r]) # 0번축이 달라서 안됨.

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 3

## 배열 분할 하기
- ### split(배열, 분할기준, axis)
    - 지정한 축을 기준으로 배열을 나눈다.. 
    - 반환값: 분할한 narray를 가진 리스트로 리턴.
    - 배열: 분할할 배열
    - 분할기준
        - 정수 : 지정 개수만큼 분할  (나눠진 배열의 size가 같아야한다.)
        - 리스트 : 분할 기준 index들 (size 바뀔수 있다 원하는 데로)
    - axis(축)
        - 분할할 기준 축을 지정한다. axis = 0 (기본) 
        - 2D의 경우 axis=0: 행 기준 분할, axis=1: 열 기준 분할
- ### vsplit(배열, 분할기준)
    - 행 기준 분할
    - split()의 axis=0과 동일
    - 분할기준
        - 정수 : 지정 개수만큼 분할
        - 리스트 : 분할 기준 index들
- ### hsplit(배열, 분할기준)
    - 열 기준 분할
    - split()의 axis=1과 동일
    - 분할기준
        - 정수 : 지정 개수만큼 분할
        - 리스트 : 분할 기준 index들
###  **주의:** 분할기준을 정수(개수)로 할 경우 분할후 원소수가 같아야 한다. 

In [8]:
import numpy as np

In [9]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
k=np.split(a,2)
print(k[0],k[1])
print(k[0].shape)
print(k[1].shape)

[0 1 2 3 4] [5 6 7 8 9]
(5,)
(5,)


In [14]:
r = np.split(a, 2)  #2개로 분할
print(type(r))
print(r[0], type(r[0]))
print(r[1], type(r[1]))
print(r.shape)

<class 'list'>
[0 1 2 3 4] <class 'numpy.ndarray'>
[5 6 7 8 9] <class 'numpy.ndarray'>


AttributeError: 'list' object has no attribute 'shape'

In [10]:
np.split(a,3) # 3개로 분할   // 10 개를 3개로 나누지 못해서 error array split does not result in an equal division
# 분할된 배열의 크기가 동일해야 한다.


ValueError: array split does not result in an equal division

In [11]:
r = np.split(a,[2,6])# index 2,6 을 기준으로 분할 // 기준이 되는 index는 다음 배열의 시작index가 된다. //분할된 배열 크기 달라도 됨 
r


[array([0, 1]), array([2, 3, 4, 5]), array([6, 7, 8, 9])]

In [20]:
k1= np.arange(20)
print(k1)
print(np.split(k1,2))
print(np.split(k1,[3,10,15]))
print(np.split(k1,3))


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])]
[array([0, 1, 2]), array([3, 4, 5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14]), array([15, 16, 17, 18, 19])]


ValueError: array split does not result in an equal division

In [12]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
#np.split(a,[4])  != np.split(a,4)  # index 4를 기준으로 나눠라 / 4 개로 분할해라
np.split(a,[4])

[array([0, 1, 2, 3]), array([4, 5, 6, 7, 8, 9])]

In [21]:
b =np.arange(16).reshape(4,4)
print(b.shape)
b

(4, 4)


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [18]:
r = np.split(b, 2)  # axis 기본값 : 0
r[0]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [19]:
r[1]

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [24]:
r = np.split(b,2, axis= 1)
r[0]

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [25]:
r[1]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [28]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [27]:
r = np.split(b,[1])
r

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [29]:
r = np.split(b,[1,3])
r

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [22]:
k2 = np.arange(25).reshape(5,5)
k2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [26]:
k1= np.split(k2,[2])
print(k1)
print(k1[0].shape)     
print(k1[1].shape)

[array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]]), array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])]
(2, 5)
(3, 5)


In [28]:
k1= np.split(k2,[2],axis=1)
k1

[array([[ 0,  1],
        [ 5,  6],
        [10, 11],
        [15, 16],
        [20, 21]]),
 array([[ 2,  3,  4],
        [ 7,  8,  9],
        [12, 13, 14],
        [17, 18, 19],
        [22, 23, 24]])]

In [36]:
from pprint import pprint  
k3= np.split(k2,[2,3],axis=1)
pprint(k3)
pprint(k3[0].shape)

[array([[ 0,  1],
       [ 5,  6],
       [10, 11],
       [15, 16],
       [20, 21]]),
 array([[ 2],
       [ 7],
       [12],
       [17],
       [22]]),
 array([[ 3,  4],
       [ 8,  9],
       [13, 14],
       [18, 19],
       [23, 24]])]
(5, 2)


In [39]:
c= np.arange(6*6*8).reshape(6,6,8)
c.shape

(6, 6, 8)

In [40]:
c

array([[[  0,   1,   2,   3,   4,   5,   6,   7],
        [  8,   9,  10,  11,  12,  13,  14,  15],
        [ 16,  17,  18,  19,  20,  21,  22,  23],
        [ 24,  25,  26,  27,  28,  29,  30,  31],
        [ 32,  33,  34,  35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44,  45,  46,  47]],

       [[ 48,  49,  50,  51,  52,  53,  54,  55],
        [ 56,  57,  58,  59,  60,  61,  62,  63],
        [ 64,  65,  66,  67,  68,  69,  70,  71],
        [ 72,  73,  74,  75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84,  85,  86,  87],
        [ 88,  89,  90,  91,  92,  93,  94,  95]],

       [[ 96,  97,  98,  99, 100, 101, 102, 103],
        [104, 105, 106, 107, 108, 109, 110, 111],
        [112, 113, 114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127],
        [128, 129, 130, 131, 132, 133, 134, 135],
        [136, 137, 138, 139, 140, 141, 142, 143]],

       [[144, 145, 146, 147, 148, 149, 150, 151],
        [152, 153, 154, 155, 156, 157, 158, 

In [41]:
r = np.split(c,2,axis = 0)
print(r[0].shape,r[1].shape)

(3, 6, 8) (3, 6, 8)


In [42]:
r = np.split(c, 2, axis=0)
print(r[0].shape, r[1].shape)

(3, 6, 8) (3, 6, 8)


In [44]:
r= np.split(c,[2,5],axis = 2)
print(r[0].shape,r[1].shape,r[2].shape)

(6, 6, 2) (6, 6, 3) (6, 6, 3)


In [43]:
r = np.split(c, [2,5], axis=2)
print(r[0].shape, r[1].shape, r[2].shape)

(6, 6, 2) (6, 6, 3) (6, 6, 3)


In [45]:
r= np.split(c,[3,5],axis = 2)
print(r[0].shape,r[1].shape,r[2].shape)
print(r[0])

(6, 6, 3) (6, 6, 2) (6, 6, 3)
[[[  0   1   2]
  [  8   9  10]
  [ 16  17  18]
  [ 24  25  26]
  [ 32  33  34]
  [ 40  41  42]]

 [[ 48  49  50]
  [ 56  57  58]
  [ 64  65  66]
  [ 72  73  74]
  [ 80  81  82]
  [ 88  89  90]]

 [[ 96  97  98]
  [104 105 106]
  [112 113 114]
  [120 121 122]
  [128 129 130]
  [136 137 138]]

 [[144 145 146]
  [152 153 154]
  [160 161 162]
  [168 169 170]
  [176 177 178]
  [184 185 186]]

 [[192 193 194]
  [200 201 202]
  [208 209 210]
  [216 217 218]
  [224 225 226]
  [232 233 234]]

 [[240 241 242]
  [248 249 250]
  [256 257 258]
  [264 265 266]
  [272 273 274]
  [280 281 282]]]


In [1]:
import numpy as np

## hsplit()/vsplit()

- ### vsplit(배열, 분할기준)
    - 행 기준 분할
    - split()의 axis=0과 동일
    - 분할기준
        - 정수 : 지정 개수만큼 분할
        - 리스트 : 분할 기준 index들
        
- ### hsplit(배열, 분할기준)
    - 열 기준 분할
    - split()의 axis=1과 동일
    - 분할기준
        - 정수 : 지정 개수만큼 분할
        - 리스트 : 분할 기준 index들
- **주의:** 분할기준을 정수(개수)로 할 경우 분할후 원소수가 같아야 한다. 

In [48]:
c = np.arange(64).reshape(8,8)
c.shape


(8, 8)

In [51]:
np.vsplit(c,[3,5])

[array([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23]]),
 array([[24, 25, 26, 27, 28, 29, 30, 31],
        [32, 33, 34, 35, 36, 37, 38, 39]]),
 array([[40, 41, 42, 43, 44, 45, 46, 47],
        [48, 49, 50, 51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60, 61, 62, 63]])]

In [7]:
# vsplit()=> split(axis =0)

r= np.vsplit(c,4)  
print(r[0].shape,r[1].shape,r[2].shape,r[3].shape)

(2, 8) (2, 8) (2, 8) (2, 8)


In [38]:
r = np.vsplit(c,[3,6])
print(r[0].shape,r[1].shape,r[2].shape)

(3, 8) (3, 8) (2, 8)


In [ ]:
# hsplit()=> split(axis =1)

In [39]:
r = np.hsplit(c,[2,5])    # index 기준이 2개니까 3조각으로 잘린다.
print(r[0].shape,r[1].shape,r[2].shape)

(8, 2) (8, 3) (8, 3)


In [40]:

r= np.hsplit(c,4) # 정수를 넣었으니 4 조각 
print(r[0].shape,r[1].shape,r[2].shape,r[3].shape)

(8, 2) (8, 2) (8, 2) (8, 2)


In [41]:
np.hsplit(c,5)  # 동일한 크기로 나누지못해서 error// 정수를 줄때는 나머지가 없이 나눠질 수 있는 숫자를 줘야한다.

ValueError: array split does not result in an equal division