# 배열을 파일에 저장 및 불러오기
- ## 바이너리 파일로 저장/불러오기
     - 차원 상관없이 저장 가능
    - ### np.save("파일경로", 배열)
        - 배열을 raw 바이너리 형식으로 저장한다. (압축하지 않은)
        - 파일명에 확장자로 **npy**를 붙인다. (무조건 붙인다. abc.xxx 해도 abc.xxx.npy 로 저장)
    - ### np.load("파일경로") 
        - 파일에 저장된 배열을 불러온다.
        - npy 확장자명을 붙여줘야한다.
    - ### np.savez("파일경로", 이름=배열, 이름=배열, ...)
        - **여러개**의 배열을 저장할 때 사용
        - 파일명에 확장자로 **npz**가 붙는다.
        - 내부적으로 <<압축해서 저장>>한다.
        - load() 함수로 불러오면 저장된 배열목록이 반환 된다. 저장시 지정한 이름을 이용해 조회 
- ## 텍스트 파일로 저장하고 불러오기
    - ### savetxt("파일경로", 배열 [, delimiter='공백']) 
        - 텍스트 형태로 저장.
        - 각 원소는 공백을 기준으로 나뉘며 delimiter 속성으로 구분자를 지정할 수 있다. (delimiter생략시 공백)
        - ## 1차원과 2차원 배열만 저장 가능하다. (3차원 이상은 저장이 안된다.)  / 텍스트로 저장하기때문에 3차원 불가능
    - ### loadtxt("파일경로" [,dtype=float, delimiter=공백])

In [4]:
import numpy as np
a = np.arange(10)
b = np.arange(12).reshape(4,3)
c = np.arange(24).reshape(4,2,3)


In [5]:
# 한개의 배열 저장
np.save('a.npy',a) #배열 a를 'a.npy' 파일로저장

In [6]:
np.save('b',b)# 확장자를 생략 해도 npy 확장자는 자동으로 붙는다.

In [5]:
np.save('c.arr',c) # 확장자는 무조건 npy 가 붙는다.

In [4]:
a2 = np.load('a.npy')
a2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
b2 = np.load('b.npy')
b2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [11]:
c2 = np.load('c.arr.npy')
c2

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]]])

In [12]:
# 한파일에 여러배열 저장 (압축)
np.savez('arr.npz', one = a, two = b, three=c)

In [8]:
np.savez('arr.npz',one =a,two=b,three=c)

In [9]:
arr = np.load('arr.npz')  # NpzFile 반환
arr

In [14]:
arr.files # 배열의 이름들을 반환

['one', 'two', 'three']

In [10]:
arr.files

['one', 'two', 'three']

In [13]:
a5=arr['one']
a5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
a3 = arr['one']
b3 = arr['two']
c3 = arr['three']

In [18]:
print(a3)

[0 1 2 3 4 5 6 7 8 9]


In [19]:
print(b3)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [20]:
print(c3)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]]]


In [5]:
# 텍스트 파일로 저장
np.savetxt('a.txt',a)

In [6]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
import numpy as np

In [3]:
np.savetxt('b.txt',b)

NameError: name 'b' is not defined

In [8]:
np.savetxt('b.csv',b,delimiter=',')

In [25]:
np.savetxt('c.txt',c)  # 3차원이라 안됨

ValueError: Expected 1D or 2D array, got 3D array instead

In [26]:
b4 = np.loadtxt('b.csv',delimiter =',')  # delimiter 안맞춰 주면 error 가 남 
b4

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [ ]:
# 절대경로 상대경로 상관없이 다 가능하다 // 여기서한거 다 상대경로