In [ ]:

# 오늘 중 (12시)

# 4 : 문제 가 잘못되서 수정했음//  16 번 잘 모르겠음
# 27,28 ,30 axis 이유 잘 모르겠음. 왜 0으로 해야하는지.

In [ ]:
1. 10, 7, 5, 90, 100 을 가지는 1차원 배열을 생성.

In [1]:
import numpy as np
arr = np.array([10,7,5,90,100]) # 규칙없이 원하는 원소를 넣어 배열을 만들때
arr

array([ 10,   7,   5,  90, 100])

In [ ]:
2. 100 ~ 200 범위의 숫자중 짝수를 가지는 배열을 생성.
# 규칙을 갖고 증감치로 설정

In [7]:
# 내가 한것 
arr1= np.arange(100,201,2) 
print(arr1)
print(arr1.shape)

[100 102 104 106 108 110 112 114 116 118 120 122 124 126 128 130 132 134
 136 138 140 142 144 146 148 150 152 154 156 158 160 162 164 166 168 170
 172 174 176 178 180 182 184 186 188 190 192 194 196 198 200]
(51,)


In [2]:
np.linspace(100,200,num=51)  # num의 개수를 세어내야되서 // 나눌 개수를 설정해야함 

array([100., 102., 104., 106., 108., 110., 112., 114., 116., 118., 120.,
       122., 124., 126., 128., 130., 132., 134., 136., 138., 140., 142.,
       144., 146., 148., 150., 152., 154., 156., 158., 160., 162., 164.,
       166., 168., 170., 172., 174., 176., 178., 180., 182., 184., 186.,
       188., 190., 192., 194., 196., 198., 200.])

In [5]:
a = np.arange(100,201)
a[a%2 ==0] # boolean 조건을 만족하는 값을 반환 [] 인덱스 연산자

array([100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124,
       126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150,
       152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176,
       178, 180, 182, 184, 186, 188, 190, 192, 194, 196, 198, 200])

In [ ]:
3. 2번에서 생성한 배열과 동일한 shape에 0을 원소로 가지는 배열 생성.

In [10]:
# 내가 한것
z = np.zeros(51,)
print(z)
print(z.shape)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0.]
(51,)


In [8]:
np.zeros(shape=arr1.shape)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
# 이것이 제일 낫다 
b=np.zeros_like(arr1)  # ones_like
b.shape

(51,)

In [ ]:
4. 1001 ~ 10000 범위의 정수 중 100의 배수만 가지는 3차원 배열을 생성. (shape은 상관없음.)
- 문제 수정했음 // 

In [16]:
# 강사님
a = np.arange(1000,9999,100)#.reshape(3,3,10)
a.shape

(90,)

In [188]:
# 내가 한것
k= np.arange(1001,10000,100)
k

array([1001, 1101, 1201, 1301, 1401, 1501, 1601, 1701, 1801, 1901, 2001,
       2101, 2201, 2301, 2401, 2501, 2601, 2701, 2801, 2901, 3001, 3101,
       3201, 3301, 3401, 3501, 3601, 3701, 3801, 3901, 4001, 4101, 4201,
       4301, 4401, 4501, 4601, 4701, 4801, 4901, 5001, 5101, 5201, 5301,
       5401, 5501, 5601, 5701, 5801, 5901, 6001, 6101, 6201, 6301, 6401,
       6501, 6601, 6701, 6801, 6901, 7001, 7101, 7201, 7301, 7401, 7501,
       7601, 7701, 7801, 7901, 8001, 8101, 8201, 8301, 8401, 8501, 8601,
       8701, 8801, 8901, 9001, 9101, 9201, 9301, 9401, 9501, 9601, 9701,
       9801, 9901])

In [189]:
print(k.size)
print(k.reshape(2,9,5))

90
[[[1001 1101 1201 1301 1401]
  [1501 1601 1701 1801 1901]
  [2001 2101 2201 2301 2401]
  [2501 2601 2701 2801 2901]
  [3001 3101 3201 3301 3401]
  [3501 3601 3701 3801 3901]
  [4001 4101 4201 4301 4401]
  [4501 4601 4701 4801 4901]
  [5001 5101 5201 5301 5401]]

 [[5501 5601 5701 5801 5901]
  [6001 6101 6201 6301 6401]
  [6501 6601 6701 6801 6901]
  [7001 7101 7201 7301 7401]
  [7501 7601 7701 7801 7901]
  [8001 8101 8201 8301 8401]
  [8501 8601 8701 8801 8901]
  [9001 9101 9201 9301 9401]
  [9501 9601 9701 9801 9901]]]


In [ ]:
5. (4,4) 형태의 단위행렬(항등행렬)을 생성.

In [17]:
np.eye(4)  # 행과열을 마음데로 조절이 가능하고 대각위치도 조정가능

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [23]:
k1 = np.identity(4)
k1

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
6. 다음 값을 가지는 배열을 생성하고 배열의 차원수(rank)와 형태, 총 원소(element)의 개수를 조회.
20, 90, 80, 100, -20, 30
50, -10, 25, 120, -40, 90

In [22]:
l=[
    [20, 90, 80, 100, -20, 30],
    [50, -10, 25, 120, -40, 90]
]

arr = np.array(l)
print("차원수 :",arr.ndim)  # 차원
print(arr.size)  # 개수
print(arr.shape)
print(arr.dtype)

차원수 : 2
12
(2, 6)
int32


In [ ]:
7. 정규분포를 따르는 난수를 가지는 (3,2,7) 형태의 배열을 생성.

In [25]:
dm = np.random.normal(size=(3,2,7))  #평균:0, 표준편차1  (-2 ~ 2)
dm

array([[[ 0.96734738,  0.98047653,  1.46204243, -0.36478589,
         -0.62642473,  1.13514707,  0.23166481],
        [-1.63238519,  0.35294601,  1.03773887, -0.57973015,
          1.4801811 , -0.54322596,  1.77256919]],

       [[ 0.88408208,  0.16455191, -2.25542936, -0.27688364,
         -1.03316271, -0.53921955, -0.41668115],
        [ 0.53834171, -1.6850949 ,  0.0217184 ,  1.20243389,
          0.1520424 , -1.10282082,  1.02539329]],

       [[ 1.38763804,  0.65270131, -0.77612943,  0.39845322,
          2.21824162,  0.07857113,  0.71970216],
        [-0.04951778, -0.41563972,  0.66764711, -0.26845938,
         -2.68199365,  0.14736276,  0.1805721 ]]])

In [36]:
dm1 = np.random.normal(10,5,size=(3,2,7))  # (평균location(loc),표준편차,size) // 난수 ---> random
print(dm1.shape)
print(dm1)


(3, 2, 7)
[[[ 0.285049   21.64027655  3.35841632  6.61203136 11.21262896
    9.33606738 11.10202655]
  [11.06630143 12.81746548  4.19250851 18.6126226  12.24506663
   17.67377758 -0.72592372]]

 [[17.83106809 12.85459324 15.55296328  3.06987083  9.56523088
    5.79822953 10.21172051]
  [13.32471461 13.74772984 11.06395038 12.59899608  8.63928535
   -0.7980305   7.39851364]]

 [[ 9.77982248 10.84747602  8.46948846  3.74000932 13.9475671
   21.7564035   0.85977615]
  [ 2.73540507 18.59411443  9.84238401 10.53951762 -3.85601188
   14.32690647 16.43466392]]]


In [ ]:
8. 1 ~ 100 사이의 정수 난수를 가지는 (4, 5) 형태의 배열을 생성한 뒤 arr.npy 파일로 저장.

In [38]:
m1 = np.random.randint(1,101,(4,5))
print(m1.shape)
print(m1)

(4, 5)
[[61 15 38 20 38]
 [99 11 76  3 84]
 [59 38 49 93  6]
 [63 10 59 92 55]]


In [39]:
np.save('arr.npy',m1)

In [ ]:
#np.save(r'c:\temp\arr.npy',m1) 절대경로

## 파일 만들어서 해보기
import os   # path 경로관련. isdir 디렉토리냐?
#배열 저장 디렉토리 : backup
if not os.path.isdir('backup'): # 현재 경로에 백업 이란 디렉토리가 없냐?
    os.mkdir('backup')          # 없으면 디렉토리 생성
np.save('backup/arr.npy',a)       

In [ ]:
9. 8번에서 저장한 arr.npy 의 배열을 불러와서 출력.

In [ ]:
# np.load('backup/arr.npy')

In [27]:
m2 =np.load('arr.npy')
m2

array([[61, 15, 38, 20, 38],
       [99, 11, 76,  3, 84],
       [59, 38, 49, 93,  6],
       [63, 10, 59, 92, 55]])

In [ ]:
10. 9번에서 불러온 배열에서 전체 값의 총합, 0번축 기준의 총합, 1번축 기준의 총합을 구하기.

In [30]:
print(np.sum(m2))
print(np.sum(m2,axis=0))
print(np.sum(m2,axis=1))

969
[282  74 222 208 183]
[172 273 245 279]


In [45]:
print(np.add.reduce(m2,axis=None))
print(np.add.reduce(m2,axis = 0))
print(np.add.reduce(m2,axis = 1))

969
[282  74 222 208 183]
[172 273 245 279]


In [ ]:
11. 임의의 Boolean 값을 가지는 (5, 10) 배열을 생성하고 True의 개수를 출력하시오.

In [31]:
bool1 = np.random.choice([True,False],size=50)
bool2=bool1.reshape(5,10)
bool2.shape  

(5, 10)

In [32]:
np.sum(bool2)  # True 개수

23

In [36]:
bool3 = np.random.choice([True,False],size=50,p=[0.1,0.9])  # False가 더많이 나올 확률을 설정
print(bool3)
print(np.sum(bool3))

[False False False False False  True False False False  True False False
 False False False False False False  True False False False False False
 False False False False False False False  True False False False False
 False False False False False False False False False False False False
 False False]
4


In [39]:
# 다른 사람 풀이  True:1, False:0
a = np.random.randint(0, 2, size = (5,10), dtype=bool)
print(a)
print(np.sum(a))

[[False  True  True False False  True False False False  True]
 [False False  True False False  True False False  True  True]
 [False False  True  True False  True False  True False False]
 [ True  True False  True  True False  True  True  True False]
 [ True False False False  True False False  True False False]]
22


In [ ]:
12-17. 아래 배열을 생성하고 12번 ~ 17번 문제는 아래 조건으로 생성한 배열을 가지고 푸세요.
 0 ~ 29 범위의 정수를 원소로 가지는 (5,6) 의 배열을 생성하고 변수에 저장.

In [41]:
d1 = np.random.randint(0,30,size=(5,6))
d1

array([[12, 29,  7,  0, 13,  0],
       [19,  5, 18, 14, 19,  5],
       [27,  7, 29,  8, 11,  2],
       [12,  5,  0,  8, 17,  5],
       [12, 23, 21,  9,  8,  9]])

In [42]:
12. index (1,1), (2,3), (1,5)의 값들 조회

SyntaxError: invalid syntax (<ipython-input-42-ec2fa3571797>, line 1)

In [43]:
d1[[1,2,1],[1,3,5]]

array([5, 8, 5])

In [ ]:
13. index (1,1), (1,2), (1,3), (2,1), (2,2), (2,3), (3,1), (3,2), (3,3)의 값들을 조회.

In [48]:
d2=d1[1:4,1:4]  # slicing 이용 차원수가 같아짐
d2

array([[ 5, 18, 14],
       [ 7, 29,  8],
       [ 5,  0,  8]])

In [49]:
d3=d1[[1,1,1,2,2,2,3,3,3],[1,2,3,1,2,3,1,2,3]]  # index 이용 .
d3

array([ 5, 18, 14,  7, 29,  8,  5,  0,  8])

In [ ]:
14. 13와 같은 index의 값들을 뒤집어서(reversing) 조회.

In [55]:
d1[1:4,1:4]  #

array([[ 5, 18, 14],
       [ 7, 29,  8],
       [ 5,  0,  8]])

In [53]:
a1=d1[3:0:-1,3:0:-1] # 4였다는것은 3까지 인덱스를 갖고오는것 1 까지니까 포함안하니까 끝인덱스를 0으로 
a1

array([[ 8,  0,  5],
       [ 8, 29,  7],
       [14, 18,  5]])

In [50]:
print(np.flip(d2))

[[ 8  0  5]
 [ 8 29  7]
 [14 18  5]]


In [63]:
print(np.flip(d1,axis=1))

[[25 21  0 19  1 10]
 [14  5 18 21  6 16]
 [ 4 20  5  2 12 21]
 [ 7  7 22 28 25 19]
 [28 24 21  0  3  8]]


In [70]:
d1

array([[10,  1, 19,  0, 21, 25],
       [16,  6, 21, 18,  5, 14],
       [21, 12,  2,  5, 20,  4],
       [19, 25, 28, 22,  7,  7],
       [ 8,  3,  0, 21, 24, 28]])

In [69]:
d1[::-1,::]

array([[ 8,  3,  0, 21, 24, 28],
       [19, 25, 28, 22,  7,  7],
       [21, 12,  2,  5, 20,  4],
       [16,  6, 21, 18,  5, 14],
       [10,  1, 19,  0, 21, 25]])

In [71]:
d1[::,::-1]

array([[25, 21,  0, 19,  1, 10],
       [14,  5, 18, 21,  6, 16],
       [ 4, 20,  5,  2, 12, 21],
       [ 7,  7, 22, 28, 25, 19],
       [28, 24, 21,  0,  3,  8]])

In [ ]:
15. 배열에서 15 이상의 원소만 조회해서 그 평균을 출력.

In [58]:
np.mean(d1[d1 >= 15])

22.444444444444443

In [57]:
sum(d1[d1>=15])/np.sum(d1>15)

22.444444444444443

In [81]:
np.sum(d1>15)

15

In [82]:
sum(d1[d1>15])

328

In [190]:
d1

array([[10,  1, 19,  0, 21, 25],
       [16,  6, 21, 18,  5, 14],
       [21, 12,  2,  5, 20,  4],
       [19, 25, 28, 22,  7,  7],
       [ 8,  3,  0, 21, 24, 28]])

In [ ]:
16. 배열에서 15이상의 원소들의 index를 조회. (0축 index, 1축 index) 형식으로 출력. 
    ex: (0,0), (0,1) 식으로 출력
- 다시 

In [60]:
d1

array([[12, 29,  7,  0, 13,  0],
       [19,  5, 18, 14, 19,  5],
       [27,  7, 29,  8, 11,  2],
       [12,  5,  0,  8, 17,  5],
       [12, 23, 21,  9,  8,  9]])

In [64]:
k=np.where(d1>=15)
k
#(k[0], 0번축 index, k[1] 1번축 index)
print(k[0],k[1])

[0 1 1 1 2 2 3 4 4] [1 0 2 4 0 2 4 1 2]


# 꼭다시 보기

In [63]:
for idx in zip(k[0],k[1]):  # 같은 인덱스끼리 묶여서 나온다.// Zip한번 반복마다 두배열의 같은 index의 값을 tuple로 묶어서 반환
    print(idx)

(0, 1)
(1, 0)
(1, 2)
(1, 4)
(2, 0)
(2, 2)
(3, 4)
(4, 1)
(4, 2)


In [65]:
for idx in zip(k[0],k[1]):  # 같은 인덱스끼리 묶여서 나온다.// Zip한번 반복마다 두배열의 같은 index의 값을 tuple로 묶어서 반환
    print(idx,end=',')

(0, 1),(1, 0),(1, 2),(1, 4),(2, 0),(2, 2),(3, 4),(4, 1),(4, 2),

In [67]:
for idx1,idx2 in zip(k[0],k[1]):  # 같은 인덱스끼리 묶여서 나온다.// Zip한번 반복마다 두배열의 같은 index의 값을 tuple로 묶어서 반환
    print(idx1,idx2)

0 1
1 0
1 2
1 4
2 0
2 2
3 4
4 1
4 2


In [ ]:
# emumerate(자료구조),zip(자료구조1, 자료구조 2,[.....]),range

In [ ]:
17. 배열을 axis 1을 기준으로 내림차순으로 정렬. 
결과
[[ 5,  4,  3,  2,  1,  0],
 [11, 10,  9,  8,  7,  6],
 [17, 16, 15, 14, 13, 12],
 [23, 22, 21, 20, 19, 18],
 [29, 28, 27, 26, 25, 24]]   

In [70]:
m=  [[ 5,  4,  3,  2,  1,  0],
 [11, 10,  9,  8,  7,  6],
 [17, 16, 15, 14, 13, 12],
 [23, 22, 21, 20, 19, 18],
 [29, 28, 27, 26, 25, 24]]

In [71]:
m2= np.array([m])
m2

array([[[ 5,  4,  3,  2,  1,  0],
        [11, 10,  9,  8,  7,  6],
        [17, 16, 15, 14, 13, 12],
        [23, 22, 21, 20, 19, 18],
        [29, 28, 27, 26, 25, 24]]])

In [76]:
m3= np.sort(m2)
m3

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29]]])

In [77]:
m4 = np.sort(m3,axis =1)
m4[::-1,::-1]

array([[[24, 25, 26, 27, 28, 29],
        [18, 19, 20, 21, 22, 23],
        [12, 13, 14, 15, 16, 17],
        [ 6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5]]])

In [ ]:
18-21. 아래 배열을 생성하고 18번 ~ 21번 문제는 아래 조건으로 생성한 배열을 가지고 푸세요.
(3, 2) shape의 배열을 생성 하시오. 

In [78]:
arr1 = np.arange(6).reshape(3,2)
arr1.shape

(3, 2)

In [ ]:
18. 배열의 shape을 (1, 3, 2) 로 변환한 배열을 생성.

In [79]:
arr2= arr1[np.newaxis,:,:]
arr2.shape

(1, 3, 2)

In [82]:
a =arr1[np.newaxis,...]
a.shape

(1, 3, 2)

In [83]:
a1 = arr1.reshape(1,3,2)
print(a1.shape)
a2 = np.expand_dims(arr1, axis=0)
print(a2.shape)

(1, 3, 2)
(1, 3, 2)


In [ ]:
19. 배열의 shape을 (1, 3, 2, 1) 로 변환한 배열을 생성.

In [85]:
arr3 = arr1[np.newaxis,:,:,np.newaxis]
print(arr3.shape)
arr4 = arr1.reshape(1,3,2,1)
arr4.shape

(1, 3, 2, 1)


(1, 3, 2, 1)

In [ ]:
20. 배열을 1차원 배열로 변환한 배열을 생성.

In [86]:
arr4=arr1.reshape(6,)
print(arr4)

[0 1 2 3 4 5]


In [88]:
f = arr1.flatten()
f

array([0, 1, 2, 3, 4, 5])

In [ ]:
21. 배열의 0번 축에 2개의 값을 추가. (추가된 배열의 shape: (5,2))//

In [113]:
arr1

array([[0, 1],
       [2, 3],
       [4, 5]])

In [89]:
arr0=np.append(arr1,[[6,7],[8,9]],axis=0)
print(arr0.shape)
print(arr0)

(5, 2)
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [91]:
arr1

array([[0, 1],
       [2, 3],
       [4, 5]])

In [90]:
# 1번 축으로 추가 
ar0=np.append(arr1,[[6,7],[8,9],[10,11]],axis=1)
ar0

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [ ]:
22-28. 다음 배열은 5명 학생의 국어, 영어, 수학, 과학 시험 점수이다. 행(axis=0)은 각 학생의 시험점수이고 컬럼(axis=1)은 과목을 가리킨다.
# 통계 자료를 처리하는 기술통계함수를 이용하는것이다.

In [3]:
l=[
 [ 60,  80,  60, 100],
 [ 80,  80,  90,  90],
 [ 90,  60,  70,  50],
 [ 40,  80,  60,  50],
 [ 60,  50,  70, 100]
]

In [4]:
jum = np.array(l)
jum
jum.shape

(5, 4)

In [ ]:
22. 각 과목별 평균점수를 조회.

In [5]:
#내가 한것
av=np.add.reduce(jum,axis=0)/5
#av1=av.reshape(1,4)
av

array([66., 70., 70., 78.])

In [7]:
mean_score=np.mean(jum,axis= 0)
mean_score

array([66., 70., 70., 78.])

In [2]:
import numpy as np

In [ ]:
23. 각 과목별 평균 점수를 성적 배열에 추가. 

In [104]:
# 내가한것
np.append(jum,av1,axis=0)

array([[ 60.,  80.,  60., 100.],
       [ 80.,  80.,  90.,  90.],
       [ 90.,  60.,  70.,  50.],
       [ 40.,  80.,  60.,  50.],
       [ 60.,  50.,  70., 100.],
       [ 66.,  70.,  70.,  78.]])

In [103]:
np.append(jum,[mean_score], axis =0)

array([[ 60.,  80.,  60., 100.],
       [ 80.,  80.,  90.,  90.],
       [ 90.,  60.,  70.,  50.],
       [ 40.,  80.,  60.,  50.],
       [ 60.,  50.,  70., 100.],
       [ 66.,  70.,  70.,  78.]])

In [ ]:
24. 각 학생들의 평균 점수 조회

In [132]:
# 내가한것
np.add.reduce(jum,axis=1)/4

array([75. , 85. , 67.5, 57.5, 70. ])

In [106]:
np.mean(jum,axis=1)
np.mean(jum,axis=1,keepdims = True)

array([[75. ],
       [85. ],
       [67.5],
       [57.5],
       [70. ]])

In [ ]:
25. 과목별로 몇번째 학생의 성적이 가장 높은지 조회

In [138]:
np.max(jum,axis=0)

array([ 90,  80,  90, 100])

In [107]:
np.argmax(jum,axis=0) +1 # 인덱스 값이아닌 몇번째 학생인지 알려고 + 1을 한것이다.//3번째 학생, 1번째 학생......

array([3, 1, 2, 1], dtype=int64)

In [142]:
jum

array([[ 60,  80,  60, 100],
       [ 80,  80,  90,  90],
       [ 90,  60,  70,  50],
       [ 40,  80,  60,  50],
       [ 60,  50,  70, 100]])

In [ ]:
26. 학생별로 어떤 과목의 점수가 가장 낮은지 조회.

In [108]:
subject = np.array(['국어','영어','수학','과학'])

In [109]:
subject[np.argmin(jum,axis=1)]

array(['국어', '국어', '과학', '국어', '영어'], dtype='<U2')

In [143]:
np.argmin(jum,axis=1)

array([0, 0, 3, 0, 1], dtype=int64)

In [ ]:
27. 각 과목별로 편차가 가장 적은 과목과 가장 큰 과목을 조회
# 과목이 아래방향이 같은 과목들이니까

In [153]:
np.argmax(np.std(jum,axis=0)) #편차 가장큰것

3

In [112]:
subject[np.argmax(np.std(jum,axis=0))]

'과학'

In [111]:
np.argmin(np.std(jum,axis=0))

2

In [117]:
np.round(np.std(jum,axis=0),2)  # np.round  반올림 

array([17.44, 12.65, 10.95, 23.15])

In [116]:
subject[np.argmin(np.std(jum,axis=0))]

'수학'

In [151]:
np.std(jum,axis=0)

array([17.43559577, 12.64911064, 10.95445115, 23.15167381])

In [ ]:
28. 학생들 중 과목간의 점수의 편차가 가장 적은 학생을 조회

In [120]:
student=['영희','철수','길동','대민','병헌']

In [122]:
minst=np.argmin(np.std(jum,axis=1))
minst

1

In [123]:
maxst=np.argmax(np.std(jum,axis=1))
maxst


4

In [119]:
np.round(np.std(jum,axis=1),2)

array([16.58,  5.  , 14.79, 14.79, 18.71])

In [ ]:
29-30 다음 두 배열을 가지고 29,30번 문제를 푸세요.

In [126]:
A=[
  [1,2,3],
  [4,5,6],
  [7,8,9]
]
B=[
  [10,20,30],
  [40,50,60],
  [70,80,90]
]

In [ ]:
29. 두 배열을 수직방향으로 합치기. 

In [133]:
print(A,B,sep ='\n')


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[10, 20, 30], [40, 50, 60], [70, 80, 90]]


In [135]:
c=np.concatenate((A,B),axis=0)
print(c)
c2 = np.vstack((A,B)) # 2차원 일때만 가능 
print(c2.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 20 30]
 [40 50 60]
 [70 80 90]]
(6, 3)


In [ ]:
30. 29에서 합친 배열을 수평방향(axis = 1 이 수평방향이니까)으로 index 2를 기준으로 나누기.

In [165]:
np.split(c,[2],axis=0)

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]])]

In [136]:
np.split(c,[2],axis=1)  #np.hsplit(),np.vsplit()

[array([[ 1,  2],
        [ 4,  5],
        [ 7,  8],
        [10, 20],
        [40, 50],
        [70, 80]]),
 array([[ 3],
        [ 6],
        [ 9],
        [30],
        [60],
        [90]])]

In [137]:
np.split(c,2,axis=0) # 2개로 나눠라// 원소수가 같아야한다.

[array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]])]

In [ ]:
31-32 다움은 7명의 학생의 점수이다. 배열을 생성한뒤 33번 ~ 35번 문제를 푸세요.

In [138]:
j=np.array([10, 50, 75, 20, 70, 50, 80])
j

array([10, 50, 75, 20, 70, 50, 80])

In [ ]:
31. 다음 배열에서 평균 이상의 점수를 받은 학생이 몇명인지 조회

In [ ]:
#
mean_score =np.mean(j)
r = score[score>=]

In [140]:
j[j>=np.mean(j)]

array([75, 70, 80])

In [141]:
np.sum(j>np.mean(j))

3

In [ ]:
32. 다음 배열에서 평균 이상의 점수를 받은 학생이 전체 학생 중 몇명인지 비율을 조회.

In [170]:
np.sum(j>np.mean(j))/j.size

0.42857142857142855

In [142]:
np.mean(j>np.mean(j))  # mean 을쓰면 비율이나온다.

0.42857142857142855

In [143]:
np.mean(j>np.mean(j))*100

42.857142857142854

In [ ]:
33-35 다음 배열은 스무명의 사람들의 연봉의 표본이다. (단위 만원) 배열을 생성한뒤 33번 ~ 35번 문제를 푸세요.

In [146]:
bong=[7650, 4210, 7260, 8020, 8200, 8740, 4960, 1420,
 5410, 9770, 2370, 7960, 8960, 2660, 7940, 5120,
 7100, 5220, 8810, 253000]
 

In [ ]:
33. 위 배열에서 상위 75% 는 얼마 이상을 받는지 조회.

In [147]:
np.quantile(bong,q=0.75)   # 75% 의 위치에 있는 연봉 = > 이것 이상 받는다.

8335.0

In [ ]:
34. 위 배열에서 하위 25%는 얼마 이하를 받는지 조회.

In [149]:
np.quantile(bong,q=0.25)

5080.0

In [148]:
#4 분위수 : 25 50 75
np.quantile(bong, q= [0.25,0.5,0.75])

array([5080., 7455., 8335.])

In [151]:
np.percentile(bong, q= [25,50,75])

array([5080., 7455., 8335.])

In [ ]:
35. 위 배열의 평균과 중앙값을 구하고 배열의 대푯값으로 어떤 것을 사용하는 것이 맞는지 적으세요.
- "중앙값"을 대푯값으로 쓰는 것이 맞음

In [175]:
np.mean(bong)  # 평균

18739.0

In [177]:
np.median(bong) # 중간값

7455.0

In [152]:
np.sort(bong)

array([  1420,   2370,   2660,   4210,   4960,   5120,   5220,   5410,
         7100,   7260,   7650,   7940,   7960,   8020,   8200,   8740,
         8810,   8960,   9770, 253000])

평균 > 중간값  차이도 많이난다.   |---------------중간값----------------평균값------------|
평균 < 중간값  차이가 많이나는경우  ---> 두경우다 극단값이 있는 배열이라는 이야기이다.---> 이런경우 대푯값으로 중앙값을 사용하는게 맞고 평균값은 대표값으로 쓰기에는 너무 왜곡된 값아다.

평균,중간값 이비슷하면 정규분포표 같은것이니 평균을 대푯값으로 써도됨