In [ ]:

# 오늘 중 (12시)

# 4 , 16 번 잘 모르겠음
# 27,28 ,30 axis 이유 잘 모르겠음. 왜 0으로 해야하는지.

In [ ]:
1. 10, 7, 5, 90, 100 을 가지는 1차원 배열을 생성.

In [2]:
import numpy as np
arr = np.array([10,7,5,90,100])
arr

array([ 10,   7,   5,  90, 100])

In [ ]:
2. 100 ~ 200 범위의 숫자중 짝수를 가지는 배열을 생성.

In [5]:
arr1= np.arange(100,201,2)
print(arr1)
print(arr1.shape)

[100 102 104 106 108 110 112 114 116 118 120 122 124 126 128 130 132 134
 136 138 140 142 144 146 148 150 152 154 156 158 160 162 164 166 168 170
 172 174 176 178 180 182 184 186 188 190 192 194 196 198 200]
(51,)


In [ ]:
3. 2번에서 생성한 배열과 동일한 shape에 0을 원소로 가지는 배열 생성.

In [10]:
z = np.zeros(51,)
print(z)
print(z.shape)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0.]
(51,)


In [ ]:
4. 1001 ~ 10000 범위의 정수 중 100의 배수만 가지는 3차원 배열을 생성. (shape은 상관없음.)
- 다시 

In [188]:
k= np.arange(1001,10000,100)
k

array([1001, 1101, 1201, 1301, 1401, 1501, 1601, 1701, 1801, 1901, 2001,
       2101, 2201, 2301, 2401, 2501, 2601, 2701, 2801, 2901, 3001, 3101,
       3201, 3301, 3401, 3501, 3601, 3701, 3801, 3901, 4001, 4101, 4201,
       4301, 4401, 4501, 4601, 4701, 4801, 4901, 5001, 5101, 5201, 5301,
       5401, 5501, 5601, 5701, 5801, 5901, 6001, 6101, 6201, 6301, 6401,
       6501, 6601, 6701, 6801, 6901, 7001, 7101, 7201, 7301, 7401, 7501,
       7601, 7701, 7801, 7901, 8001, 8101, 8201, 8301, 8401, 8501, 8601,
       8701, 8801, 8901, 9001, 9101, 9201, 9301, 9401, 9501, 9601, 9701,
       9801, 9901])

In [189]:
print(k.size)
print(k.reshape(2,9,5))

90
[[[1001 1101 1201 1301 1401]
  [1501 1601 1701 1801 1901]
  [2001 2101 2201 2301 2401]
  [2501 2601 2701 2801 2901]
  [3001 3101 3201 3301 3401]
  [3501 3601 3701 3801 3901]
  [4001 4101 4201 4301 4401]
  [4501 4601 4701 4801 4901]
  [5001 5101 5201 5301 5401]]

 [[5501 5601 5701 5801 5901]
  [6001 6101 6201 6301 6401]
  [6501 6601 6701 6801 6901]
  [7001 7101 7201 7301 7401]
  [7501 7601 7701 7801 7901]
  [8001 8101 8201 8301 8401]
  [8501 8601 8701 8801 8901]
  [9001 9101 9201 9301 9401]
  [9501 9601 9701 9801 9901]]]


In [ ]:
5. (4,4) 형태의 단위행렬(항등행렬)을 생성.

In [23]:
k1 = np.identity(4)
k1

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
6. 다음 값을 가지는 배열을 생성하고 배열의 차원수(rank)와 형태, 총 원소(element)의 개수를 조회.
20, 90, 80, 100, -20, 30
50, -10, 25, 120, -40, 90

In [28]:
l=[
    [20, 90, 80, 100, -20, 30],
    [50, -10, 25, 120, -40, 90]
]

arr = np.array(l)
print(arr.ndim)  # 차원
print(arr.size)  # 개수

2
12


In [ ]:
7. 정규분포를 따르는 난수를 가지는 (3,2,7) 형태의 배열을 생성.

In [36]:
dm = np.random.normal(10,5,size=(3,2,7))  # (평균,표준편차,size)
print(dm.shape)
print(dm)


(3, 2, 7)
[[[ 0.285049   21.64027655  3.35841632  6.61203136 11.21262896
    9.33606738 11.10202655]
  [11.06630143 12.81746548  4.19250851 18.6126226  12.24506663
   17.67377758 -0.72592372]]

 [[17.83106809 12.85459324 15.55296328  3.06987083  9.56523088
    5.79822953 10.21172051]
  [13.32471461 13.74772984 11.06395038 12.59899608  8.63928535
   -0.7980305   7.39851364]]

 [[ 9.77982248 10.84747602  8.46948846  3.74000932 13.9475671
   21.7564035   0.85977615]
  [ 2.73540507 18.59411443  9.84238401 10.53951762 -3.85601188
   14.32690647 16.43466392]]]


In [ ]:
8. 1 ~ 100 사이의 정수 난수를 가지는 (4, 5) 형태의 배열을 생성한 뒤 arr.npy 파일로 저장.

In [38]:
m1 = np.random.randint(1,101,(4,5))
print(m1.shape)
print(m1)

(4, 5)
[[61 15 38 20 38]
 [99 11 76  3 84]
 [59 38 49 93  6]
 [63 10 59 92 55]]


In [39]:
np.save('arr.npy',m1)

In [ ]:
9. 8번에서 저장한 arr.npy 의 배열을 불러와서 출력.

In [40]:
m2 =np.load('arr.npy')
m2

array([[61, 15, 38, 20, 38],
       [99, 11, 76,  3, 84],
       [59, 38, 49, 93,  6],
       [63, 10, 59, 92, 55]])

In [ ]:
10. 9번에서 불러온 배열에서 전체 값의 총합, 0번축 기준의 총합, 1번축 기준의 총합을 구하기.

In [45]:
print(np.add.reduce(m2,axis=None))
print(np.add.reduce(m2,axis = 0))
print(np.add.reduce(m2,axis = 1))

969
[282  74 222 208 183]
[172 273 245 279]


In [ ]:
11. 임의의 Boolean 값을 가지는 (5, 10) 배열을 생성하고 True의 개수를 출력하시오.

In [50]:
bool1 = np.random.choice([True,False],size=50)
bool2=bool1.reshape(5,10)
bool2.shape  

(5, 10)

In [51]:
np.sum(bool2)  # True 개수

23

In [ ]:
12-17. 아래 배열을 생성하고 12번 ~ 17번 문제는 아래 조건으로 생성한 배열을 가지고 푸세요.
 0 ~ 29 범위의 정수를 원소로 가지는 (5,6) 의 배열을 생성하고 변수에 저장.

In [52]:
d1 = np.random.randint(0,30,size=(5,6))
d1

array([[10,  1, 19,  0, 21, 25],
       [16,  6, 21, 18,  5, 14],
       [21, 12,  2,  5, 20,  4],
       [19, 25, 28, 22,  7,  7],
       [ 8,  3,  0, 21, 24, 28]])

In [ ]:
12. index (1,1), (2,3), (1,5)의 값들 조회

In [56]:
d1[[1,2,1],[1,3,5]]

array([ 6,  5, 14])

In [ ]:
13. index (1,1), (1,2), (1,3), (2,1), (2,2), (2,3), (3,1), (3,2), (3,3)의 값들을 조회.

In [57]:
d1[[1,1,1,2,2,2,3,3,3],[1,2,3,1,2,3,1,2,3]]

array([ 6, 21, 18, 12,  2,  5, 25, 28, 22])

In [ ]:
14. 13와 같은 index의 값들을 뒤집어서(reversing) 조회.

In [62]:
print(np.flip(d1))

[[28 24 21  0  3  8]
 [ 7  7 22 28 25 19]
 [ 4 20  5  2 12 21]
 [14  5 18 21  6 16]
 [25 21  0 19  1 10]]


In [63]:
print(np.flip(d1,axis=1))

[[25 21  0 19  1 10]
 [14  5 18 21  6 16]
 [ 4 20  5  2 12 21]
 [ 7  7 22 28 25 19]
 [28 24 21  0  3  8]]


In [70]:
d1

array([[10,  1, 19,  0, 21, 25],
       [16,  6, 21, 18,  5, 14],
       [21, 12,  2,  5, 20,  4],
       [19, 25, 28, 22,  7,  7],
       [ 8,  3,  0, 21, 24, 28]])

In [69]:
d1[::-1,::]

array([[ 8,  3,  0, 21, 24, 28],
       [19, 25, 28, 22,  7,  7],
       [21, 12,  2,  5, 20,  4],
       [16,  6, 21, 18,  5, 14],
       [10,  1, 19,  0, 21, 25]])

In [71]:
d1[::,::-1]

array([[25, 21,  0, 19,  1, 10],
       [14,  5, 18, 21,  6, 16],
       [ 4, 20,  5,  2, 12, 21],
       [ 7,  7, 22, 28, 25, 19],
       [28, 24, 21,  0,  3,  8]])

In [ ]:
15. 배열에서 15 이상의 원소만 조회해서 그 평균을 출력.

In [80]:
sum(d1[d1>15])/np.sum(d1>15)

21.866666666666667

In [81]:
np.sum(d1>15)

15

In [82]:
sum(d1[d1>15])

328

In [190]:
d1

array([[10,  1, 19,  0, 21, 25],
       [16,  6, 21, 18,  5, 14],
       [21, 12,  2,  5, 20,  4],
       [19, 25, 28, 22,  7,  7],
       [ 8,  3,  0, 21, 24, 28]])

In [ ]:
16. 배열에서 15이상의 원소들의 index를 조회. (0축 index, 1축 index) 형식으로 출력. 
    ex: (0,0), (0,1) 식으로 출력
- 다시 

In [191]:
k=np.where(d1>15)
k

(array([0, 0, 0, 1, 1, 1, 2, 2, 3, 3, 3, 3, 4, 4, 4], dtype=int64),
 array([2, 4, 5, 0, 2, 3, 0, 4, 0, 1, 2, 3, 3, 4, 5], dtype=int64))

In [197]:
k1= np.array(k).reshape(30,)
k1

array([0, 0, 0, 1, 1, 1, 2, 2, 3, 3, 3, 3, 4, 4, 4, 2, 4, 5, 0, 2, 3, 0,
       4, 0, 1, 2, 3, 3, 4, 5], dtype=int64)

In [ ]:
17. 배열을 axis 1을 기준으로 내림차순으로 정렬. 
결과
[[ 5,  4,  3,  2,  1,  0],
 [11, 10,  9,  8,  7,  6],
 [17, 16, 15, 14, 13, 12],
 [23, 22, 21, 20, 19, 18],
 [29, 28, 27, 26, 25, 24]]   

In [88]:
m=  [[ 5,  4,  3,  2,  1,  0],
 [11, 10,  9,  8,  7,  6],
 [17, 16, 15, 14, 13, 12],
 [23, 22, 21, 20, 19, 18],
 [29, 28, 27, 26, 25, 24]]

In [89]:
m2= np.array([m])
m2

array([[[ 5,  4,  3,  2,  1,  0],
        [11, 10,  9,  8,  7,  6],
        [17, 16, 15, 14, 13, 12],
        [23, 22, 21, 20, 19, 18],
        [29, 28, 27, 26, 25, 24]]])

In [105]:
m3 = np.sort(m2,axis =1)
m3[::-1,::-1]

array([[[29, 28, 27, 26, 25, 24],
        [23, 22, 21, 20, 19, 18],
        [17, 16, 15, 14, 13, 12],
        [11, 10,  9,  8,  7,  6],
        [ 5,  4,  3,  2,  1,  0]]])

In [ ]:
18-21. 아래 배열을 생성하고 18번 ~ 21번 문제는 아래 조건으로 생성한 배열을 가지고 푸세요.
(3, 2) shape의 배열을 생성 하시오. 

In [108]:
arr1 = np.arange(6).reshape(3,2)
arr1.shape

(3, 2)

In [ ]:
18. 배열의 shape을 (1, 3, 2) 로 변환한 배열을 생성.

In [110]:
arr2= arr1[np.newaxis,:,:]
arr2.shape

(1, 3, 2)

In [ ]:
19. 배열의 shape을 (1, 3, 2, 1) 로 변환한 배열을 생성.

In [111]:
arr3 = arr1[np.newaxis,:,:,np.newaxis]
arr3.shape

(1, 3, 2, 1)

In [ ]:
20. 배열을 1차원 배열로 변환한 배열을 생성.

In [112]:
arr4=arr1.reshape(6,)
arr4

array([0, 1, 2, 3, 4, 5])

In [ ]:
21. 배열의 0번 축에 2개의 값을 추가. (추가된 배열의 shape: (5,2))//

In [113]:
arr1

array([[0, 1],
       [2, 3],
       [4, 5]])

In [116]:
arr0=np.append(arr1,[[6,7],[8,9]],axis=0)
arr0.shape

(5, 2)

In [ ]:
22-28. 다음 배열은 5명 학생의 국어, 영어, 수학, 과학 시험 점수이다. 행(axis=0)은 각 학생의 시험점수이고 컬럼(axis=1)은 과목을 가리킨다.

In [119]:
l=[
 [ 60,  80,  60, 100],
 [ 80,  80,  90,  90],
 [ 90,  60,  70,  50],
 [ 40,  80,  60,  50],
 [ 60,  50,  70, 100]
]

In [127]:
jum = np.array(l)
jum
jum.shape

(5, 4)

In [ ]:
22. 각 과목별 평균점수를 조회.

In [130]:
av=np.add.reduce(jum,axis=0)/5
av1=av.reshape(1,4)

In [ ]:
23. 각 과목별 평균 점수를 성적 배열에 추가. 

In [131]:
np.append(jum,av1,axis=0)

array([[ 60.,  80.,  60., 100.],
       [ 80.,  80.,  90.,  90.],
       [ 90.,  60.,  70.,  50.],
       [ 40.,  80.,  60.,  50.],
       [ 60.,  50.,  70., 100.],
       [ 66.,  70.,  70.,  78.]])

In [ ]:
24. 각 학생들의 평균 점수 조회

In [132]:
np.add.reduce(jum,axis=1)/4

array([75. , 85. , 67.5, 57.5, 70. ])

In [ ]:
25. 과목별로 몇번째 학생의 성적이 가장 높은지 조회

In [138]:
np.max(jum,axis=0)

array([ 90,  80,  90, 100])

In [137]:
np.argmax(jum,axis=0)

array([2, 0, 1, 0], dtype=int64)

In [142]:
jum

array([[ 60,  80,  60, 100],
       [ 80,  80,  90,  90],
       [ 90,  60,  70,  50],
       [ 40,  80,  60,  50],
       [ 60,  50,  70, 100]])

In [ ]:
26. 학생별로 어떤 과목의 점수가 가장 낮은지 조회.

In [143]:
np.argmin(jum,axis=1)

array([0, 0, 3, 0, 1], dtype=int64)

In [ ]:
27. 각 과목별로 편차가 가장 적은 과목과 가장 큰 과목을 조회
# 왜 axis =0 으로 해야하는지 모르겠음 axis=1 방향이 과목인데..

In [153]:
np.argmax(np.std(jum,axis=0))

3

In [152]:
np.argmin(np.std(jum,axis=0))

2

In [151]:
np.std(jum,axis=0)

array([17.43559577, 12.64911064, 10.95445115, 23.15167381])

In [ ]:
28. 학생들 중 과목간의 점수의 편차가 가장 적은 학생을 조회

In [155]:
np.argmin(np.std(jum,axis=1))

1

In [ ]:
29-30 다음 두 배열을 가지고 29,30번 문제를 푸세요.

In [161]:
A=[
  [1,2,3],
  [4,5,6],
  [7,8,9]
]
B=[
  [10,20,30],
  [40,50,60],
  [70,80,90]
]

In [ ]:
29. 두 배열을 수직방향으로 합치기. 

In [163]:
c=np.concatenate((A,B),axis=0)
c

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [ ]:
30. 29에서 합친 배열을 수평방향으로 index 2를 기준으로 나누기.

In [165]:
np.split(c,[2],axis=0)

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]])]

In [ ]:
31-32 다움은 7명의 학생의 점수이다. 배열을 생성한뒤 33번 ~ 35번 문제를 푸세요.

In [166]:
j=np.array([10, 50, 75, 20, 70, 50, 80])
j

array([10, 50, 75, 20, 70, 50, 80])

In [ ]:
31. 다음 배열에서 평균 이상의 점수를 받은 학생이 몇명인지 조회

In [168]:
j[j>np.mean(j)]

array([75, 70, 80])

In [169]:
np.sum(j>np.mean(j))

3

In [ ]:
32. 다음 배열에서 평균 이상의 점수를 받은 학생이 전체 학생 중 몇명인지 비율을 조회.

In [170]:
np.sum(j>np.mean(j))/j.size

0.42857142857142855

In [ ]:
33-35 다음 배열은 스무명의 사람들의 연봉의 표본이다. (단위 만원) 배열을 생성한뒤 33번 ~ 35번 문제를 푸세요.

In [171]:
bong=[7650, 4210, 7260, 8020, 8200, 8740, 4960, 1420,
 5410, 9770, 2370, 7960, 8960, 2660, 7940, 5120,
 7100, 5220, 8810, 253000]
 

In [ ]:
33. 위 배열에서 상위 75% 는 얼마 이상을 받는지 조회.

In [173]:
np.quantile(bong,q=0.75)   # 75% 의 위치에 있는 연봉 = > 이것 이상 받는다.

8335.0

In [ ]:
34. 위 배열에서 하위 25%는 얼마 이하를 받는지 조회.

In [174]:
np.quantile(bong,q=0.25)

5080.0

In [ ]:
35. 위 배열의 평균과 중앙값을 구하고 배열의 대푯값으로 어떤 것을 사용하는 것이 맞는지 적으세요.
- "중앙값"을 대푯값으로 쓰는 것이 맞음

In [175]:
np.mean(bong)

18739.0

In [177]:
np.median(bong)

7455.0